/*
 * acep
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.volcengine.acep.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * UpdateProductResourceRequest
 */



public class UpdateProductResourceRequest {
  @SerializedName("ApplyDataSize")
  private Integer applyDataSize = null;

  @SerializedName("ProductId")
  private String productId = null;

  @SerializedName("VolcRegion")
  private String volcRegion = null;

  public UpdateProductResourceRequest applyDataSize(Integer applyDataSize) {
    this.applyDataSize = applyDataSize;
    return this;
  }

   /**
   * Get applyDataSize
   * @return applyDataSize
  **/
  @Schema(description = "")
  public Integer getApplyDataSize() {
    return applyDataSize;
  }

  public void setApplyDataSize(Integer applyDataSize) {
    this.applyDataSize = applyDataSize;
  }

  public UpdateProductResourceRequest productId(String productId) {
    this.productId = productId;
    return this;
  }

   /**
   * Get productId
   * @return productId
  **/
  @NotNull
  @Schema(required = true, description = "")
  public String getProductId() {
    return productId;
  }

  public void setProductId(String productId) {
    this.productId = productId;
  }

  public UpdateProductResourceRequest volcRegion(String volcRegion) {
    this.volcRegion = volcRegion;
    return this;
  }

   /**
   * Get volcRegion
   * @return volcRegion
  **/
  @Schema(description = "")
  public String getVolcRegion() {
    return volcRegion;
  }

  public void setVolcRegion(String volcRegion) {
    this.volcRegion = volcRegion;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateProductResourceRequest updateProductResourceRequest = (UpdateProductResourceRequest) o;
    return Objects.equals(this.applyDataSize, updateProductResourceRequest.applyDataSize) &&
        Objects.equals(this.productId, updateProductResourceRequest.productId) &&
        Objects.equals(this.volcRegion, updateProductResourceRequest.volcRegion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(applyDataSize, productId, volcRegion);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateProductResourceRequest {\n");
    
    sb.append("    applyDataSize: ").append(toIndentedString(applyDataSize)).append("\n");
    sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
    sb.append("    volcRegion: ").append(toIndentedString(volcRegion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
