/*
 * vefaas
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.volcengine.vefaas.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.volcengine.vefaas.model.AllowEgressForListSandboxesOutput;
import com.volcengine.vefaas.model.DenyEgressForListSandboxesOutput;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * NetworkRulesForListSandboxesOutput
 */



public class NetworkRulesForListSandboxesOutput {
  @SerializedName("AllowEgress")
  private List<AllowEgressForListSandboxesOutput> allowEgress = null;

  @SerializedName("AllowEgressAccess")
  private Boolean allowEgressAccess = null;

  @SerializedName("DenyEgress")
  private List<DenyEgressForListSandboxesOutput> denyEgress = null;

  @SerializedName("MaxEgressCps")
  private Long maxEgressCps = null;

  public NetworkRulesForListSandboxesOutput allowEgress(List<AllowEgressForListSandboxesOutput> allowEgress) {
    this.allowEgress = allowEgress;
    return this;
  }

  public NetworkRulesForListSandboxesOutput addAllowEgressItem(AllowEgressForListSandboxesOutput allowEgressItem) {
    if (this.allowEgress == null) {
      this.allowEgress = new ArrayList<AllowEgressForListSandboxesOutput>();
    }
    this.allowEgress.add(allowEgressItem);
    return this;
  }

   /**
   * Get allowEgress
   * @return allowEgress
  **/
  @Valid
  @Schema(description = "")
  public List<AllowEgressForListSandboxesOutput> getAllowEgress() {
    return allowEgress;
  }

  public void setAllowEgress(List<AllowEgressForListSandboxesOutput> allowEgress) {
    this.allowEgress = allowEgress;
  }

  public NetworkRulesForListSandboxesOutput allowEgressAccess(Boolean allowEgressAccess) {
    this.allowEgressAccess = allowEgressAccess;
    return this;
  }

   /**
   * Get allowEgressAccess
   * @return allowEgressAccess
  **/
  @Schema(description = "")
  public Boolean isAllowEgressAccess() {
    return allowEgressAccess;
  }

  public void setAllowEgressAccess(Boolean allowEgressAccess) {
    this.allowEgressAccess = allowEgressAccess;
  }

  public NetworkRulesForListSandboxesOutput denyEgress(List<DenyEgressForListSandboxesOutput> denyEgress) {
    this.denyEgress = denyEgress;
    return this;
  }

  public NetworkRulesForListSandboxesOutput addDenyEgressItem(DenyEgressForListSandboxesOutput denyEgressItem) {
    if (this.denyEgress == null) {
      this.denyEgress = new ArrayList<DenyEgressForListSandboxesOutput>();
    }
    this.denyEgress.add(denyEgressItem);
    return this;
  }

   /**
   * Get denyEgress
   * @return denyEgress
  **/
  @Valid
  @Schema(description = "")
  public List<DenyEgressForListSandboxesOutput> getDenyEgress() {
    return denyEgress;
  }

  public void setDenyEgress(List<DenyEgressForListSandboxesOutput> denyEgress) {
    this.denyEgress = denyEgress;
  }

  public NetworkRulesForListSandboxesOutput maxEgressCps(Long maxEgressCps) {
    this.maxEgressCps = maxEgressCps;
    return this;
  }

   /**
   * Get maxEgressCps
   * @return maxEgressCps
  **/
  @Schema(description = "")
  public Long getMaxEgressCps() {
    return maxEgressCps;
  }

  public void setMaxEgressCps(Long maxEgressCps) {
    this.maxEgressCps = maxEgressCps;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NetworkRulesForListSandboxesOutput networkRulesForListSandboxesOutput = (NetworkRulesForListSandboxesOutput) o;
    return Objects.equals(this.allowEgress, networkRulesForListSandboxesOutput.allowEgress) &&
        Objects.equals(this.allowEgressAccess, networkRulesForListSandboxesOutput.allowEgressAccess) &&
        Objects.equals(this.denyEgress, networkRulesForListSandboxesOutput.denyEgress) &&
        Objects.equals(this.maxEgressCps, networkRulesForListSandboxesOutput.maxEgressCps);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allowEgress, allowEgressAccess, denyEgress, maxEgressCps);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NetworkRulesForListSandboxesOutput {\n");
    
    sb.append("    allowEgress: ").append(toIndentedString(allowEgress)).append("\n");
    sb.append("    allowEgressAccess: ").append(toIndentedString(allowEgressAccess)).append("\n");
    sb.append("    denyEgress: ").append(toIndentedString(denyEgress)).append("\n");
    sb.append("    maxEgressCps: ").append(toIndentedString(maxEgressCps)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
