/*
 * vod20260101
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.volcengine.vod20260101.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.volcengine.vod20260101.model.CommonTypeForDescribeVodDomainConfigOutput;
import com.volcengine.vod20260101.model.RegularTypeForDescribeVodDomainConfigOutput;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * ReferersTypeForDescribeVodDomainConfigOutput
 */



public class ReferersTypeForDescribeVodDomainConfigOutput {
  @SerializedName("CommonType")
  private CommonTypeForDescribeVodDomainConfigOutput commonType = null;

  @SerializedName("RegularType")
  private RegularTypeForDescribeVodDomainConfigOutput regularType = null;

  public ReferersTypeForDescribeVodDomainConfigOutput commonType(CommonTypeForDescribeVodDomainConfigOutput commonType) {
    this.commonType = commonType;
    return this;
  }

   /**
   * Get commonType
   * @return commonType
  **/
  @Valid
  @Schema(description = "")
  public CommonTypeForDescribeVodDomainConfigOutput getCommonType() {
    return commonType;
  }

  public void setCommonType(CommonTypeForDescribeVodDomainConfigOutput commonType) {
    this.commonType = commonType;
  }

  public ReferersTypeForDescribeVodDomainConfigOutput regularType(RegularTypeForDescribeVodDomainConfigOutput regularType) {
    this.regularType = regularType;
    return this;
  }

   /**
   * Get regularType
   * @return regularType
  **/
  @Valid
  @Schema(description = "")
  public RegularTypeForDescribeVodDomainConfigOutput getRegularType() {
    return regularType;
  }

  public void setRegularType(RegularTypeForDescribeVodDomainConfigOutput regularType) {
    this.regularType = regularType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReferersTypeForDescribeVodDomainConfigOutput referersTypeForDescribeVodDomainConfigOutput = (ReferersTypeForDescribeVodDomainConfigOutput) o;
    return Objects.equals(this.commonType, referersTypeForDescribeVodDomainConfigOutput.commonType) &&
        Objects.equals(this.regularType, referersTypeForDescribeVodDomainConfigOutput.regularType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(commonType, regularType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReferersTypeForDescribeVodDomainConfigOutput {\n");
    
    sb.append("    commonType: ").append(toIndentedString(commonType)).append("\n");
    sb.append("    regularType: ").append(toIndentedString(regularType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
