/*
 * billing
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.volcengine.billing.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * QueryBalanceAcctResponse
 */



public class QueryBalanceAcctResponse extends com.volcengine.model.AbstractResponse {
  @SerializedName("AccountID")
  private Integer accountID = null;

  @SerializedName("ArrearsBalance")
  private String arrearsBalance = null;

  @SerializedName("AvailableBalance")
  private String availableBalance = null;

  @SerializedName("CashBalance")
  private String cashBalance = null;

  @SerializedName("CreditLimit")
  private String creditLimit = null;

  @SerializedName("FreezeAmount")
  private String freezeAmount = null;

  public QueryBalanceAcctResponse accountID(Integer accountID) {
    this.accountID = accountID;
    return this;
  }

   /**
   * Get accountID
   * @return accountID
  **/
  @Schema(description = "")
  public Integer getAccountID() {
    return accountID;
  }

  public void setAccountID(Integer accountID) {
    this.accountID = accountID;
  }

  public QueryBalanceAcctResponse arrearsBalance(String arrearsBalance) {
    this.arrearsBalance = arrearsBalance;
    return this;
  }

   /**
   * Get arrearsBalance
   * @return arrearsBalance
  **/
  @Schema(description = "")
  public String getArrearsBalance() {
    return arrearsBalance;
  }

  public void setArrearsBalance(String arrearsBalance) {
    this.arrearsBalance = arrearsBalance;
  }

  public QueryBalanceAcctResponse availableBalance(String availableBalance) {
    this.availableBalance = availableBalance;
    return this;
  }

   /**
   * Get availableBalance
   * @return availableBalance
  **/
  @Schema(description = "")
  public String getAvailableBalance() {
    return availableBalance;
  }

  public void setAvailableBalance(String availableBalance) {
    this.availableBalance = availableBalance;
  }

  public QueryBalanceAcctResponse cashBalance(String cashBalance) {
    this.cashBalance = cashBalance;
    return this;
  }

   /**
   * Get cashBalance
   * @return cashBalance
  **/
  @Schema(description = "")
  public String getCashBalance() {
    return cashBalance;
  }

  public void setCashBalance(String cashBalance) {
    this.cashBalance = cashBalance;
  }

  public QueryBalanceAcctResponse creditLimit(String creditLimit) {
    this.creditLimit = creditLimit;
    return this;
  }

   /**
   * Get creditLimit
   * @return creditLimit
  **/
  @Schema(description = "")
  public String getCreditLimit() {
    return creditLimit;
  }

  public void setCreditLimit(String creditLimit) {
    this.creditLimit = creditLimit;
  }

  public QueryBalanceAcctResponse freezeAmount(String freezeAmount) {
    this.freezeAmount = freezeAmount;
    return this;
  }

   /**
   * Get freezeAmount
   * @return freezeAmount
  **/
  @Schema(description = "")
  public String getFreezeAmount() {
    return freezeAmount;
  }

  public void setFreezeAmount(String freezeAmount) {
    this.freezeAmount = freezeAmount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QueryBalanceAcctResponse queryBalanceAcctResponse = (QueryBalanceAcctResponse) o;
    return Objects.equals(this.accountID, queryBalanceAcctResponse.accountID) &&
        Objects.equals(this.arrearsBalance, queryBalanceAcctResponse.arrearsBalance) &&
        Objects.equals(this.availableBalance, queryBalanceAcctResponse.availableBalance) &&
        Objects.equals(this.cashBalance, queryBalanceAcctResponse.cashBalance) &&
        Objects.equals(this.creditLimit, queryBalanceAcctResponse.creditLimit) &&
        Objects.equals(this.freezeAmount, queryBalanceAcctResponse.freezeAmount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountID, arrearsBalance, availableBalance, cashBalance, creditLimit, freezeAmount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueryBalanceAcctResponse {\n");
    
    sb.append("    accountID: ").append(toIndentedString(accountID)).append("\n");
    sb.append("    arrearsBalance: ").append(toIndentedString(arrearsBalance)).append("\n");
    sb.append("    availableBalance: ").append(toIndentedString(availableBalance)).append("\n");
    sb.append("    cashBalance: ").append(toIndentedString(cashBalance)).append("\n");
    sb.append("    creditLimit: ").append(toIndentedString(creditLimit)).append("\n");
    sb.append("    freezeAmount: ").append(toIndentedString(freezeAmount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
