/*
 * dcdn
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.volcengine.dcdn.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.volcengine.dcdn.model.HeaderInfoForListDomainConfigOutput;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * RequestHeaderForListDomainConfigOutput
 */


public class RequestHeaderForListDomainConfigOutput {
  @SerializedName("Enable")
  private Boolean enable = null;

  @SerializedName("HeaderInfo")
  private List<HeaderInfoForListDomainConfigOutput> headerInfo = null;

  public RequestHeaderForListDomainConfigOutput enable(Boolean enable) {
    this.enable = enable;
    return this;
  }

   /**
   * Get enable
   * @return enable
  **/
  @Schema(description = "")
  public Boolean isEnable() {
    return enable;
  }

  public void setEnable(Boolean enable) {
    this.enable = enable;
  }

  public RequestHeaderForListDomainConfigOutput headerInfo(List<HeaderInfoForListDomainConfigOutput> headerInfo) {
    this.headerInfo = headerInfo;
    return this;
  }

  public RequestHeaderForListDomainConfigOutput addHeaderInfoItem(HeaderInfoForListDomainConfigOutput headerInfoItem) {
    if (this.headerInfo == null) {
      this.headerInfo = new ArrayList<HeaderInfoForListDomainConfigOutput>();
    }
    this.headerInfo.add(headerInfoItem);
    return this;
  }

   /**
   * Get headerInfo
   * @return headerInfo
  **/
  @Valid
  @Schema(description = "")
  public List<HeaderInfoForListDomainConfigOutput> getHeaderInfo() {
    return headerInfo;
  }

  public void setHeaderInfo(List<HeaderInfoForListDomainConfigOutput> headerInfo) {
    this.headerInfo = headerInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequestHeaderForListDomainConfigOutput requestHeaderForListDomainConfigOutput = (RequestHeaderForListDomainConfigOutput) o;
    return Objects.equals(this.enable, requestHeaderForListDomainConfigOutput.enable) &&
        Objects.equals(this.headerInfo, requestHeaderForListDomainConfigOutput.headerInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enable, headerInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequestHeaderForListDomainConfigOutput {\n");
    
    sb.append("    enable: ").append(toIndentedString(enable)).append("\n");
    sb.append("    headerInfo: ").append(toIndentedString(headerInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
