/*
 * vpc
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.volcengine.vpc.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * EipAddressForDescribeEipAddressesBillingOutput
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-05-24T15:52:48.516414+08:00[Asia/Shanghai]")
public class EipAddressForDescribeEipAddressesBillingOutput {
  @SerializedName("AllocationId")
  private String allocationId = null;

  @SerializedName("BillingType")
  private Integer billingType = null;

  @SerializedName("ExpiredTime")
  private String expiredTime = null;

  @SerializedName("OverdueReclaimTime")
  private String overdueReclaimTime = null;

  @SerializedName("OverdueTime")
  private String overdueTime = null;

  @SerializedName("ReclaimTime")
  private String reclaimTime = null;

  @SerializedName("RemainRenewTimes")
  private Integer remainRenewTimes = null;

  @SerializedName("RenewPeriodTimes")
  private Integer renewPeriodTimes = null;

  @SerializedName("RenewType")
  private Integer renewType = null;

  @SerializedName("Status")
  private Integer status = null;

  public EipAddressForDescribeEipAddressesBillingOutput allocationId(String allocationId) {
    this.allocationId = allocationId;
    return this;
  }

   /**
   * Get allocationId
   * @return allocationId
  **/
  @Schema(description = "")
  public String getAllocationId() {
    return allocationId;
  }

  public void setAllocationId(String allocationId) {
    this.allocationId = allocationId;
  }

  public EipAddressForDescribeEipAddressesBillingOutput billingType(Integer billingType) {
    this.billingType = billingType;
    return this;
  }

   /**
   * Get billingType
   * @return billingType
  **/
  @Schema(description = "")
  public Integer getBillingType() {
    return billingType;
  }

  public void setBillingType(Integer billingType) {
    this.billingType = billingType;
  }

  public EipAddressForDescribeEipAddressesBillingOutput expiredTime(String expiredTime) {
    this.expiredTime = expiredTime;
    return this;
  }

   /**
   * Get expiredTime
   * @return expiredTime
  **/
  @Schema(description = "")
  public String getExpiredTime() {
    return expiredTime;
  }

  public void setExpiredTime(String expiredTime) {
    this.expiredTime = expiredTime;
  }

  public EipAddressForDescribeEipAddressesBillingOutput overdueReclaimTime(String overdueReclaimTime) {
    this.overdueReclaimTime = overdueReclaimTime;
    return this;
  }

   /**
   * Get overdueReclaimTime
   * @return overdueReclaimTime
  **/
  @Schema(description = "")
  public String getOverdueReclaimTime() {
    return overdueReclaimTime;
  }

  public void setOverdueReclaimTime(String overdueReclaimTime) {
    this.overdueReclaimTime = overdueReclaimTime;
  }

  public EipAddressForDescribeEipAddressesBillingOutput overdueTime(String overdueTime) {
    this.overdueTime = overdueTime;
    return this;
  }

   /**
   * Get overdueTime
   * @return overdueTime
  **/
  @Schema(description = "")
  public String getOverdueTime() {
    return overdueTime;
  }

  public void setOverdueTime(String overdueTime) {
    this.overdueTime = overdueTime;
  }

  public EipAddressForDescribeEipAddressesBillingOutput reclaimTime(String reclaimTime) {
    this.reclaimTime = reclaimTime;
    return this;
  }

   /**
   * Get reclaimTime
   * @return reclaimTime
  **/
  @Schema(description = "")
  public String getReclaimTime() {
    return reclaimTime;
  }

  public void setReclaimTime(String reclaimTime) {
    this.reclaimTime = reclaimTime;
  }

  public EipAddressForDescribeEipAddressesBillingOutput remainRenewTimes(Integer remainRenewTimes) {
    this.remainRenewTimes = remainRenewTimes;
    return this;
  }

   /**
   * Get remainRenewTimes
   * @return remainRenewTimes
  **/
  @Schema(description = "")
  public Integer getRemainRenewTimes() {
    return remainRenewTimes;
  }

  public void setRemainRenewTimes(Integer remainRenewTimes) {
    this.remainRenewTimes = remainRenewTimes;
  }

  public EipAddressForDescribeEipAddressesBillingOutput renewPeriodTimes(Integer renewPeriodTimes) {
    this.renewPeriodTimes = renewPeriodTimes;
    return this;
  }

   /**
   * Get renewPeriodTimes
   * @return renewPeriodTimes
  **/
  @Schema(description = "")
  public Integer getRenewPeriodTimes() {
    return renewPeriodTimes;
  }

  public void setRenewPeriodTimes(Integer renewPeriodTimes) {
    this.renewPeriodTimes = renewPeriodTimes;
  }

  public EipAddressForDescribeEipAddressesBillingOutput renewType(Integer renewType) {
    this.renewType = renewType;
    return this;
  }

   /**
   * Get renewType
   * @return renewType
  **/
  @Schema(description = "")
  public Integer getRenewType() {
    return renewType;
  }

  public void setRenewType(Integer renewType) {
    this.renewType = renewType;
  }

  public EipAddressForDescribeEipAddressesBillingOutput status(Integer status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(description = "")
  public Integer getStatus() {
    return status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EipAddressForDescribeEipAddressesBillingOutput eipAddressForDescribeEipAddressesBillingOutput = (EipAddressForDescribeEipAddressesBillingOutput) o;
    return Objects.equals(this.allocationId, eipAddressForDescribeEipAddressesBillingOutput.allocationId) &&
        Objects.equals(this.billingType, eipAddressForDescribeEipAddressesBillingOutput.billingType) &&
        Objects.equals(this.expiredTime, eipAddressForDescribeEipAddressesBillingOutput.expiredTime) &&
        Objects.equals(this.overdueReclaimTime, eipAddressForDescribeEipAddressesBillingOutput.overdueReclaimTime) &&
        Objects.equals(this.overdueTime, eipAddressForDescribeEipAddressesBillingOutput.overdueTime) &&
        Objects.equals(this.reclaimTime, eipAddressForDescribeEipAddressesBillingOutput.reclaimTime) &&
        Objects.equals(this.remainRenewTimes, eipAddressForDescribeEipAddressesBillingOutput.remainRenewTimes) &&
        Objects.equals(this.renewPeriodTimes, eipAddressForDescribeEipAddressesBillingOutput.renewPeriodTimes) &&
        Objects.equals(this.renewType, eipAddressForDescribeEipAddressesBillingOutput.renewType) &&
        Objects.equals(this.status, eipAddressForDescribeEipAddressesBillingOutput.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allocationId, billingType, expiredTime, overdueReclaimTime, overdueTime, reclaimTime, remainRenewTimes, renewPeriodTimes, renewType, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EipAddressForDescribeEipAddressesBillingOutput {\n");
    
    sb.append("    allocationId: ").append(toIndentedString(allocationId)).append("\n");
    sb.append("    billingType: ").append(toIndentedString(billingType)).append("\n");
    sb.append("    expiredTime: ").append(toIndentedString(expiredTime)).append("\n");
    sb.append("    overdueReclaimTime: ").append(toIndentedString(overdueReclaimTime)).append("\n");
    sb.append("    overdueTime: ").append(toIndentedString(overdueTime)).append("\n");
    sb.append("    reclaimTime: ").append(toIndentedString(reclaimTime)).append("\n");
    sb.append("    remainRenewTimes: ").append(toIndentedString(remainRenewTimes)).append("\n");
    sb.append("    renewPeriodTimes: ").append(toIndentedString(renewPeriodTimes)).append("\n");
    sb.append("    renewType: ").append(toIndentedString(renewType)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
