/*
 * volc_observe
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.volcengine.volcobserve.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.volcengine.volcobserve.model.ConditionForListAlertTemplatesOutput;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * LevelConditionForListAlertTemplatesOutput
 */



public class LevelConditionForListAlertTemplatesOutput {
  @SerializedName("Conditions")
  private List<ConditionForListAlertTemplatesOutput> conditions = null;

  /**
   * Gets or Sets level
   */
  @JsonAdapter(LevelEnum.Adapter.class)
  public enum LevelEnum {
    @SerializedName("notice")
    NOTICE("notice"),
    @SerializedName("warning")
    WARNING("warning"),
    @SerializedName("critical")
    CRITICAL("critical");

    private String value;

    LevelEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static LevelEnum fromValue(String input) {
      for (LevelEnum b : LevelEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<LevelEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final LevelEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public LevelEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return LevelEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("Level")
  private LevelEnum level = null;

  public LevelConditionForListAlertTemplatesOutput conditions(List<ConditionForListAlertTemplatesOutput> conditions) {
    this.conditions = conditions;
    return this;
  }

  public LevelConditionForListAlertTemplatesOutput addConditionsItem(ConditionForListAlertTemplatesOutput conditionsItem) {
    if (this.conditions == null) {
      this.conditions = new ArrayList<ConditionForListAlertTemplatesOutput>();
    }
    this.conditions.add(conditionsItem);
    return this;
  }

   /**
   * Get conditions
   * @return conditions
  **/
  @Valid
  @Schema(description = "")
  public List<ConditionForListAlertTemplatesOutput> getConditions() {
    return conditions;
  }

  public void setConditions(List<ConditionForListAlertTemplatesOutput> conditions) {
    this.conditions = conditions;
  }

  public LevelConditionForListAlertTemplatesOutput level(LevelEnum level) {
    this.level = level;
    return this;
  }

   /**
   * Get level
   * @return level
  **/
  @Schema(description = "")
  public LevelEnum getLevel() {
    return level;
  }

  public void setLevel(LevelEnum level) {
    this.level = level;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LevelConditionForListAlertTemplatesOutput levelConditionForListAlertTemplatesOutput = (LevelConditionForListAlertTemplatesOutput) o;
    return Objects.equals(this.conditions, levelConditionForListAlertTemplatesOutput.conditions) &&
        Objects.equals(this.level, levelConditionForListAlertTemplatesOutput.level);
  }

  @Override
  public int hashCode() {
    return Objects.hash(conditions, level);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LevelConditionForListAlertTemplatesOutput {\n");
    
    sb.append("    conditions: ").append(toIndentedString(conditions)).append("\n");
    sb.append("    level: ").append(toIndentedString(level)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
