/*
 * id
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.volcengine.id.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.volcengine.id.model.RootForGetDepartmentTreeOutput;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * GetDepartmentTreeResponse
 */



public class GetDepartmentTreeResponse extends com.volcengine.model.AbstractResponse {
  @SerializedName("Roots")
  private List<RootForGetDepartmentTreeOutput> roots = null;

  public GetDepartmentTreeResponse roots(List<RootForGetDepartmentTreeOutput> roots) {
    this.roots = roots;
    return this;
  }

  public GetDepartmentTreeResponse addRootsItem(RootForGetDepartmentTreeOutput rootsItem) {
    if (this.roots == null) {
      this.roots = new ArrayList<RootForGetDepartmentTreeOutput>();
    }
    this.roots.add(rootsItem);
    return this;
  }

   /**
   * Get roots
   * @return roots
  **/
  @Valid
  @Schema(description = "")
  public List<RootForGetDepartmentTreeOutput> getRoots() {
    return roots;
  }

  public void setRoots(List<RootForGetDepartmentTreeOutput> roots) {
    this.roots = roots;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetDepartmentTreeResponse getDepartmentTreeResponse = (GetDepartmentTreeResponse) o;
    return Objects.equals(this.roots, getDepartmentTreeResponse.roots);
  }

  @Override
  public int hashCode() {
    return Objects.hash(roots);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetDepartmentTreeResponse {\n");
    
    sb.append("    roots: ").append(toIndentedString(roots)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
