/*
 * id
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.volcengine.id.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.volcengine.id.model.ApiKeyMetadataForUpdateApiKeyCredentialProviderInput;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * UpdateApiKeyCredentialProviderRequest
 */



public class UpdateApiKeyCredentialProviderRequest {
  @SerializedName("ApiKey")
  private String apiKey = null;

  @SerializedName("ApiKeyMetadata")
  private List<ApiKeyMetadataForUpdateApiKeyCredentialProviderInput> apiKeyMetadata = null;

  @SerializedName("Name")
  private String name = null;

  @SerializedName("PoolName")
  private String poolName = null;

  public UpdateApiKeyCredentialProviderRequest apiKey(String apiKey) {
    this.apiKey = apiKey;
    return this;
  }

   /**
   * Get apiKey
   * @return apiKey
  **/
  @Schema(description = "")
  public String getApiKey() {
    return apiKey;
  }

  public void setApiKey(String apiKey) {
    this.apiKey = apiKey;
  }

  public UpdateApiKeyCredentialProviderRequest apiKeyMetadata(List<ApiKeyMetadataForUpdateApiKeyCredentialProviderInput> apiKeyMetadata) {
    this.apiKeyMetadata = apiKeyMetadata;
    return this;
  }

  public UpdateApiKeyCredentialProviderRequest addApiKeyMetadataItem(ApiKeyMetadataForUpdateApiKeyCredentialProviderInput apiKeyMetadataItem) {
    if (this.apiKeyMetadata == null) {
      this.apiKeyMetadata = new ArrayList<ApiKeyMetadataForUpdateApiKeyCredentialProviderInput>();
    }
    this.apiKeyMetadata.add(apiKeyMetadataItem);
    return this;
  }

   /**
   * Get apiKeyMetadata
   * @return apiKeyMetadata
  **/
  @Valid
  @Schema(description = "")
  public List<ApiKeyMetadataForUpdateApiKeyCredentialProviderInput> getApiKeyMetadata() {
    return apiKeyMetadata;
  }

  public void setApiKeyMetadata(List<ApiKeyMetadataForUpdateApiKeyCredentialProviderInput> apiKeyMetadata) {
    this.apiKeyMetadata = apiKeyMetadata;
  }

  public UpdateApiKeyCredentialProviderRequest name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @NotNull
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public UpdateApiKeyCredentialProviderRequest poolName(String poolName) {
    this.poolName = poolName;
    return this;
  }

   /**
   * Get poolName
   * @return poolName
  **/
  @Schema(description = "")
  public String getPoolName() {
    return poolName;
  }

  public void setPoolName(String poolName) {
    this.poolName = poolName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateApiKeyCredentialProviderRequest updateApiKeyCredentialProviderRequest = (UpdateApiKeyCredentialProviderRequest) o;
    return Objects.equals(this.apiKey, updateApiKeyCredentialProviderRequest.apiKey) &&
        Objects.equals(this.apiKeyMetadata, updateApiKeyCredentialProviderRequest.apiKeyMetadata) &&
        Objects.equals(this.name, updateApiKeyCredentialProviderRequest.name) &&
        Objects.equals(this.poolName, updateApiKeyCredentialProviderRequest.poolName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(apiKey, apiKeyMetadata, name, poolName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateApiKeyCredentialProviderRequest {\n");
    
    sb.append("    apiKey: ").append(toIndentedString(apiKey)).append("\n");
    sb.append("    apiKeyMetadata: ").append(toIndentedString(apiKeyMetadata)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    poolName: ").append(toIndentedString(poolName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
