/*
 * seccenter20240508
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.volcengine.seccenter20240508.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * GetRaspAlarmStatisticsResponse
 */



public class GetRaspAlarmStatisticsResponse extends com.volcengine.model.AbstractResponse {
  @SerializedName("AlarmCriticalCount")
  private Long alarmCriticalCount = null;

  @SerializedName("AlarmHighCount")
  private Long alarmHighCount = null;

  @SerializedName("AlarmLowCount")
  private Long alarmLowCount = null;

  @SerializedName("AlarmMediumCount")
  private Long alarmMediumCount = null;

  @SerializedName("AlarmProcessedCount")
  private Long alarmProcessedCount = null;

  @SerializedName("AlarmTotal")
  private Long alarmTotal = null;

  @SerializedName("AlarmWhiteCount")
  private Long alarmWhiteCount = null;

  @SerializedName("IsolateFileCount")
  private Long isolateFileCount = null;

  @SerializedName("IsolateTodayCount")
  private Long isolateTodayCount = null;

  @SerializedName("PrecisionDefenseCount")
  private Long precisionDefenseCount = null;

  @SerializedName("PrecisionDefenseTodayCount")
  private Long precisionDefenseTodayCount = null;

  @SerializedName("UnhandledTodayCount")
  private Long unhandledTodayCount = null;

  public GetRaspAlarmStatisticsResponse alarmCriticalCount(Long alarmCriticalCount) {
    this.alarmCriticalCount = alarmCriticalCount;
    return this;
  }

   /**
   * Get alarmCriticalCount
   * @return alarmCriticalCount
  **/
  @Schema(description = "")
  public Long getAlarmCriticalCount() {
    return alarmCriticalCount;
  }

  public void setAlarmCriticalCount(Long alarmCriticalCount) {
    this.alarmCriticalCount = alarmCriticalCount;
  }

  public GetRaspAlarmStatisticsResponse alarmHighCount(Long alarmHighCount) {
    this.alarmHighCount = alarmHighCount;
    return this;
  }

   /**
   * Get alarmHighCount
   * @return alarmHighCount
  **/
  @Schema(description = "")
  public Long getAlarmHighCount() {
    return alarmHighCount;
  }

  public void setAlarmHighCount(Long alarmHighCount) {
    this.alarmHighCount = alarmHighCount;
  }

  public GetRaspAlarmStatisticsResponse alarmLowCount(Long alarmLowCount) {
    this.alarmLowCount = alarmLowCount;
    return this;
  }

   /**
   * Get alarmLowCount
   * @return alarmLowCount
  **/
  @Schema(description = "")
  public Long getAlarmLowCount() {
    return alarmLowCount;
  }

  public void setAlarmLowCount(Long alarmLowCount) {
    this.alarmLowCount = alarmLowCount;
  }

  public GetRaspAlarmStatisticsResponse alarmMediumCount(Long alarmMediumCount) {
    this.alarmMediumCount = alarmMediumCount;
    return this;
  }

   /**
   * Get alarmMediumCount
   * @return alarmMediumCount
  **/
  @Schema(description = "")
  public Long getAlarmMediumCount() {
    return alarmMediumCount;
  }

  public void setAlarmMediumCount(Long alarmMediumCount) {
    this.alarmMediumCount = alarmMediumCount;
  }

  public GetRaspAlarmStatisticsResponse alarmProcessedCount(Long alarmProcessedCount) {
    this.alarmProcessedCount = alarmProcessedCount;
    return this;
  }

   /**
   * Get alarmProcessedCount
   * @return alarmProcessedCount
  **/
  @Schema(description = "")
  public Long getAlarmProcessedCount() {
    return alarmProcessedCount;
  }

  public void setAlarmProcessedCount(Long alarmProcessedCount) {
    this.alarmProcessedCount = alarmProcessedCount;
  }

  public GetRaspAlarmStatisticsResponse alarmTotal(Long alarmTotal) {
    this.alarmTotal = alarmTotal;
    return this;
  }

   /**
   * Get alarmTotal
   * @return alarmTotal
  **/
  @Schema(description = "")
  public Long getAlarmTotal() {
    return alarmTotal;
  }

  public void setAlarmTotal(Long alarmTotal) {
    this.alarmTotal = alarmTotal;
  }

  public GetRaspAlarmStatisticsResponse alarmWhiteCount(Long alarmWhiteCount) {
    this.alarmWhiteCount = alarmWhiteCount;
    return this;
  }

   /**
   * Get alarmWhiteCount
   * @return alarmWhiteCount
  **/
  @Schema(description = "")
  public Long getAlarmWhiteCount() {
    return alarmWhiteCount;
  }

  public void setAlarmWhiteCount(Long alarmWhiteCount) {
    this.alarmWhiteCount = alarmWhiteCount;
  }

  public GetRaspAlarmStatisticsResponse isolateFileCount(Long isolateFileCount) {
    this.isolateFileCount = isolateFileCount;
    return this;
  }

   /**
   * Get isolateFileCount
   * @return isolateFileCount
  **/
  @Schema(description = "")
  public Long getIsolateFileCount() {
    return isolateFileCount;
  }

  public void setIsolateFileCount(Long isolateFileCount) {
    this.isolateFileCount = isolateFileCount;
  }

  public GetRaspAlarmStatisticsResponse isolateTodayCount(Long isolateTodayCount) {
    this.isolateTodayCount = isolateTodayCount;
    return this;
  }

   /**
   * Get isolateTodayCount
   * @return isolateTodayCount
  **/
  @Schema(description = "")
  public Long getIsolateTodayCount() {
    return isolateTodayCount;
  }

  public void setIsolateTodayCount(Long isolateTodayCount) {
    this.isolateTodayCount = isolateTodayCount;
  }

  public GetRaspAlarmStatisticsResponse precisionDefenseCount(Long precisionDefenseCount) {
    this.precisionDefenseCount = precisionDefenseCount;
    return this;
  }

   /**
   * Get precisionDefenseCount
   * @return precisionDefenseCount
  **/
  @Schema(description = "")
  public Long getPrecisionDefenseCount() {
    return precisionDefenseCount;
  }

  public void setPrecisionDefenseCount(Long precisionDefenseCount) {
    this.precisionDefenseCount = precisionDefenseCount;
  }

  public GetRaspAlarmStatisticsResponse precisionDefenseTodayCount(Long precisionDefenseTodayCount) {
    this.precisionDefenseTodayCount = precisionDefenseTodayCount;
    return this;
  }

   /**
   * Get precisionDefenseTodayCount
   * @return precisionDefenseTodayCount
  **/
  @Schema(description = "")
  public Long getPrecisionDefenseTodayCount() {
    return precisionDefenseTodayCount;
  }

  public void setPrecisionDefenseTodayCount(Long precisionDefenseTodayCount) {
    this.precisionDefenseTodayCount = precisionDefenseTodayCount;
  }

  public GetRaspAlarmStatisticsResponse unhandledTodayCount(Long unhandledTodayCount) {
    this.unhandledTodayCount = unhandledTodayCount;
    return this;
  }

   /**
   * Get unhandledTodayCount
   * @return unhandledTodayCount
  **/
  @Schema(description = "")
  public Long getUnhandledTodayCount() {
    return unhandledTodayCount;
  }

  public void setUnhandledTodayCount(Long unhandledTodayCount) {
    this.unhandledTodayCount = unhandledTodayCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetRaspAlarmStatisticsResponse getRaspAlarmStatisticsResponse = (GetRaspAlarmStatisticsResponse) o;
    return Objects.equals(this.alarmCriticalCount, getRaspAlarmStatisticsResponse.alarmCriticalCount) &&
        Objects.equals(this.alarmHighCount, getRaspAlarmStatisticsResponse.alarmHighCount) &&
        Objects.equals(this.alarmLowCount, getRaspAlarmStatisticsResponse.alarmLowCount) &&
        Objects.equals(this.alarmMediumCount, getRaspAlarmStatisticsResponse.alarmMediumCount) &&
        Objects.equals(this.alarmProcessedCount, getRaspAlarmStatisticsResponse.alarmProcessedCount) &&
        Objects.equals(this.alarmTotal, getRaspAlarmStatisticsResponse.alarmTotal) &&
        Objects.equals(this.alarmWhiteCount, getRaspAlarmStatisticsResponse.alarmWhiteCount) &&
        Objects.equals(this.isolateFileCount, getRaspAlarmStatisticsResponse.isolateFileCount) &&
        Objects.equals(this.isolateTodayCount, getRaspAlarmStatisticsResponse.isolateTodayCount) &&
        Objects.equals(this.precisionDefenseCount, getRaspAlarmStatisticsResponse.precisionDefenseCount) &&
        Objects.equals(this.precisionDefenseTodayCount, getRaspAlarmStatisticsResponse.precisionDefenseTodayCount) &&
        Objects.equals(this.unhandledTodayCount, getRaspAlarmStatisticsResponse.unhandledTodayCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(alarmCriticalCount, alarmHighCount, alarmLowCount, alarmMediumCount, alarmProcessedCount, alarmTotal, alarmWhiteCount, isolateFileCount, isolateTodayCount, precisionDefenseCount, precisionDefenseTodayCount, unhandledTodayCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetRaspAlarmStatisticsResponse {\n");
    
    sb.append("    alarmCriticalCount: ").append(toIndentedString(alarmCriticalCount)).append("\n");
    sb.append("    alarmHighCount: ").append(toIndentedString(alarmHighCount)).append("\n");
    sb.append("    alarmLowCount: ").append(toIndentedString(alarmLowCount)).append("\n");
    sb.append("    alarmMediumCount: ").append(toIndentedString(alarmMediumCount)).append("\n");
    sb.append("    alarmProcessedCount: ").append(toIndentedString(alarmProcessedCount)).append("\n");
    sb.append("    alarmTotal: ").append(toIndentedString(alarmTotal)).append("\n");
    sb.append("    alarmWhiteCount: ").append(toIndentedString(alarmWhiteCount)).append("\n");
    sb.append("    isolateFileCount: ").append(toIndentedString(isolateFileCount)).append("\n");
    sb.append("    isolateTodayCount: ").append(toIndentedString(isolateTodayCount)).append("\n");
    sb.append("    precisionDefenseCount: ").append(toIndentedString(precisionDefenseCount)).append("\n");
    sb.append("    precisionDefenseTodayCount: ").append(toIndentedString(precisionDefenseTodayCount)).append("\n");
    sb.append("    unhandledTodayCount: ").append(toIndentedString(unhandledTodayCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
