/*
 * vod20250101
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.volcengine.vod20250101.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.volcengine.vod20250101.model.SubtitleRecognitionConfigForSubmitAITranslationWorkflowInput;
import com.volcengine.vod20250101.model.VoiceCloneConfigForSubmitAITranslationWorkflowInput;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * OperatorConfigForSubmitAITranslationWorkflowInput
 */



public class OperatorConfigForSubmitAITranslationWorkflowInput {
  @SerializedName("SubtitleRecognitionConfig")
  private SubtitleRecognitionConfigForSubmitAITranslationWorkflowInput subtitleRecognitionConfig = null;

  @SerializedName("VoiceCloneConfig")
  private VoiceCloneConfigForSubmitAITranslationWorkflowInput voiceCloneConfig = null;

  public OperatorConfigForSubmitAITranslationWorkflowInput subtitleRecognitionConfig(SubtitleRecognitionConfigForSubmitAITranslationWorkflowInput subtitleRecognitionConfig) {
    this.subtitleRecognitionConfig = subtitleRecognitionConfig;
    return this;
  }

   /**
   * Get subtitleRecognitionConfig
   * @return subtitleRecognitionConfig
  **/
  @Valid
  @Schema(description = "")
  public SubtitleRecognitionConfigForSubmitAITranslationWorkflowInput getSubtitleRecognitionConfig() {
    return subtitleRecognitionConfig;
  }

  public void setSubtitleRecognitionConfig(SubtitleRecognitionConfigForSubmitAITranslationWorkflowInput subtitleRecognitionConfig) {
    this.subtitleRecognitionConfig = subtitleRecognitionConfig;
  }

  public OperatorConfigForSubmitAITranslationWorkflowInput voiceCloneConfig(VoiceCloneConfigForSubmitAITranslationWorkflowInput voiceCloneConfig) {
    this.voiceCloneConfig = voiceCloneConfig;
    return this;
  }

   /**
   * Get voiceCloneConfig
   * @return voiceCloneConfig
  **/
  @Valid
  @Schema(description = "")
  public VoiceCloneConfigForSubmitAITranslationWorkflowInput getVoiceCloneConfig() {
    return voiceCloneConfig;
  }

  public void setVoiceCloneConfig(VoiceCloneConfigForSubmitAITranslationWorkflowInput voiceCloneConfig) {
    this.voiceCloneConfig = voiceCloneConfig;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OperatorConfigForSubmitAITranslationWorkflowInput operatorConfigForSubmitAITranslationWorkflowInput = (OperatorConfigForSubmitAITranslationWorkflowInput) o;
    return Objects.equals(this.subtitleRecognitionConfig, operatorConfigForSubmitAITranslationWorkflowInput.subtitleRecognitionConfig) &&
        Objects.equals(this.voiceCloneConfig, operatorConfigForSubmitAITranslationWorkflowInput.voiceCloneConfig);
  }

  @Override
  public int hashCode() {
    return Objects.hash(subtitleRecognitionConfig, voiceCloneConfig);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OperatorConfigForSubmitAITranslationWorkflowInput {\n");
    
    sb.append("    subtitleRecognitionConfig: ").append(toIndentedString(subtitleRecognitionConfig)).append("\n");
    sb.append("    voiceCloneConfig: ").append(toIndentedString(voiceCloneConfig)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
