/*
 * kafka
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.volcengine.kafka.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.volcengine.kafka.model.MessageListForQueryMessageByOffsetsOutput;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * QueryMessageByOffsetsResponse
 */



public class QueryMessageByOffsetsResponse extends com.volcengine.model.AbstractResponse {
  @SerializedName("HasMoreMessage")
  private Boolean hasMoreMessage = null;

  @SerializedName("MessageList")
  private List<MessageListForQueryMessageByOffsetsOutput> messageList = null;

  public QueryMessageByOffsetsResponse hasMoreMessage(Boolean hasMoreMessage) {
    this.hasMoreMessage = hasMoreMessage;
    return this;
  }

   /**
   * Get hasMoreMessage
   * @return hasMoreMessage
  **/
  @Schema(description = "")
  public Boolean isHasMoreMessage() {
    return hasMoreMessage;
  }

  public void setHasMoreMessage(Boolean hasMoreMessage) {
    this.hasMoreMessage = hasMoreMessage;
  }

  public QueryMessageByOffsetsResponse messageList(List<MessageListForQueryMessageByOffsetsOutput> messageList) {
    this.messageList = messageList;
    return this;
  }

  public QueryMessageByOffsetsResponse addMessageListItem(MessageListForQueryMessageByOffsetsOutput messageListItem) {
    if (this.messageList == null) {
      this.messageList = new ArrayList<MessageListForQueryMessageByOffsetsOutput>();
    }
    this.messageList.add(messageListItem);
    return this;
  }

   /**
   * Get messageList
   * @return messageList
  **/
  @Valid
  @Schema(description = "")
  public List<MessageListForQueryMessageByOffsetsOutput> getMessageList() {
    return messageList;
  }

  public void setMessageList(List<MessageListForQueryMessageByOffsetsOutput> messageList) {
    this.messageList = messageList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QueryMessageByOffsetsResponse queryMessageByOffsetsResponse = (QueryMessageByOffsetsResponse) o;
    return Objects.equals(this.hasMoreMessage, queryMessageByOffsetsResponse.hasMoreMessage) &&
        Objects.equals(this.messageList, queryMessageByOffsetsResponse.messageList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hasMoreMessage, messageList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueryMessageByOffsetsResponse {\n");
    
    sb.append("    hasMoreMessage: ").append(toIndentedString(hasMoreMessage)).append("\n");
    sb.append("    messageList: ").append(toIndentedString(messageList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
