/*
 * ml_platform20240701
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.volcengine.mlplatform20240701.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * FlexibleResourceClaimForListDevInstancesOutput
 */



public class FlexibleResourceClaimForListDevInstancesOutput {
  @SerializedName("Cpu")
  private Double cpu = null;

  @SerializedName("Family")
  private String family = null;

  @SerializedName("GpuCount")
  private Double gpuCount = null;

  @SerializedName("GpuType")
  private String gpuType = null;

  @SerializedName("MemoryGiB")
  private Double memoryGiB = null;

  @SerializedName("RdmaEniCount")
  private Integer rdmaEniCount = null;

  public FlexibleResourceClaimForListDevInstancesOutput cpu(Double cpu) {
    this.cpu = cpu;
    return this;
  }

   /**
   * Get cpu
   * @return cpu
  **/
  @Schema(description = "")
  public Double getCpu() {
    return cpu;
  }

  public void setCpu(Double cpu) {
    this.cpu = cpu;
  }

  public FlexibleResourceClaimForListDevInstancesOutput family(String family) {
    this.family = family;
    return this;
  }

   /**
   * Get family
   * @return family
  **/
  @Schema(description = "")
  public String getFamily() {
    return family;
  }

  public void setFamily(String family) {
    this.family = family;
  }

  public FlexibleResourceClaimForListDevInstancesOutput gpuCount(Double gpuCount) {
    this.gpuCount = gpuCount;
    return this;
  }

   /**
   * Get gpuCount
   * @return gpuCount
  **/
  @Schema(description = "")
  public Double getGpuCount() {
    return gpuCount;
  }

  public void setGpuCount(Double gpuCount) {
    this.gpuCount = gpuCount;
  }

  public FlexibleResourceClaimForListDevInstancesOutput gpuType(String gpuType) {
    this.gpuType = gpuType;
    return this;
  }

   /**
   * Get gpuType
   * @return gpuType
  **/
  @Schema(description = "")
  public String getGpuType() {
    return gpuType;
  }

  public void setGpuType(String gpuType) {
    this.gpuType = gpuType;
  }

  public FlexibleResourceClaimForListDevInstancesOutput memoryGiB(Double memoryGiB) {
    this.memoryGiB = memoryGiB;
    return this;
  }

   /**
   * Get memoryGiB
   * @return memoryGiB
  **/
  @Schema(description = "")
  public Double getMemoryGiB() {
    return memoryGiB;
  }

  public void setMemoryGiB(Double memoryGiB) {
    this.memoryGiB = memoryGiB;
  }

  public FlexibleResourceClaimForListDevInstancesOutput rdmaEniCount(Integer rdmaEniCount) {
    this.rdmaEniCount = rdmaEniCount;
    return this;
  }

   /**
   * Get rdmaEniCount
   * @return rdmaEniCount
  **/
  @Schema(description = "")
  public Integer getRdmaEniCount() {
    return rdmaEniCount;
  }

  public void setRdmaEniCount(Integer rdmaEniCount) {
    this.rdmaEniCount = rdmaEniCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FlexibleResourceClaimForListDevInstancesOutput flexibleResourceClaimForListDevInstancesOutput = (FlexibleResourceClaimForListDevInstancesOutput) o;
    return Objects.equals(this.cpu, flexibleResourceClaimForListDevInstancesOutput.cpu) &&
        Objects.equals(this.family, flexibleResourceClaimForListDevInstancesOutput.family) &&
        Objects.equals(this.gpuCount, flexibleResourceClaimForListDevInstancesOutput.gpuCount) &&
        Objects.equals(this.gpuType, flexibleResourceClaimForListDevInstancesOutput.gpuType) &&
        Objects.equals(this.memoryGiB, flexibleResourceClaimForListDevInstancesOutput.memoryGiB) &&
        Objects.equals(this.rdmaEniCount, flexibleResourceClaimForListDevInstancesOutput.rdmaEniCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cpu, family, gpuCount, gpuType, memoryGiB, rdmaEniCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FlexibleResourceClaimForListDevInstancesOutput {\n");
    
    sb.append("    cpu: ").append(toIndentedString(cpu)).append("\n");
    sb.append("    family: ").append(toIndentedString(family)).append("\n");
    sb.append("    gpuCount: ").append(toIndentedString(gpuCount)).append("\n");
    sb.append("    gpuType: ").append(toIndentedString(gpuType)).append("\n");
    sb.append("    memoryGiB: ").append(toIndentedString(memoryGiB)).append("\n");
    sb.append("    rdmaEniCount: ").append(toIndentedString(rdmaEniCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
