/*
 * ml_platform20240701
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.volcengine.mlplatform20240701.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.volcengine.mlplatform20240701.model.ComputeResourceForGetResourceQueueOutput;
import com.volcengine.mlplatform20240701.model.QuotaAllocatedForGetResourceQueueOutput;
import com.volcengine.mlplatform20240701.model.QuotaCapabilityForGetResourceQueueOutput;
import com.volcengine.mlplatform20240701.model.RulesForGetResourceQueueOutput;
import com.volcengine.mlplatform20240701.model.SharedQuotaAllocatedForGetResourceQueueOutput;
import com.volcengine.mlplatform20240701.model.StatusForGetResourceQueueOutput;
import com.volcengine.mlplatform20240701.model.SystemQuotaAllocatedForGetResourceQueueOutput;
import com.volcengine.mlplatform20240701.model.VolumeResourceForGetResourceQueueOutput;
import com.volcengine.mlplatform20240701.model.WorkloadInfoForGetResourceQueueOutput;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * GetResourceQueueResponse
 */



public class GetResourceQueueResponse extends com.volcengine.model.AbstractResponse {
  @SerializedName("ChargeType")
  private String chargeType = null;

  @SerializedName("ComputeResources")
  private List<ComputeResourceForGetResourceQueueOutput> computeResources = null;

  @SerializedName("Description")
  private String description = null;

  @SerializedName("Id")
  private String id = null;

  @SerializedName("Name")
  private String name = null;

  @SerializedName("ProjectName")
  private String projectName = null;

  @SerializedName("QuotaAllocated")
  private QuotaAllocatedForGetResourceQueueOutput quotaAllocated = null;

  @SerializedName("QuotaCapability")
  private QuotaCapabilityForGetResourceQueueOutput quotaCapability = null;

  @SerializedName("ResourceGroupId")
  private String resourceGroupId = null;

  @SerializedName("Rules")
  private RulesForGetResourceQueueOutput rules = null;

  @SerializedName("Shareable")
  private Boolean shareable = null;

  @SerializedName("SharedQuotaAllocated")
  private SharedQuotaAllocatedForGetResourceQueueOutput sharedQuotaAllocated = null;

  @SerializedName("Status")
  private StatusForGetResourceQueueOutput status = null;

  @SerializedName("SystemQuotaAllocated")
  private SystemQuotaAllocatedForGetResourceQueueOutput systemQuotaAllocated = null;

  @SerializedName("VolumeResources")
  private List<VolumeResourceForGetResourceQueueOutput> volumeResources = null;

  @SerializedName("WorkloadInfos")
  private List<WorkloadInfoForGetResourceQueueOutput> workloadInfos = null;

  @SerializedName("ZoneIds")
  private List<String> zoneIds = null;

  public GetResourceQueueResponse chargeType(String chargeType) {
    this.chargeType = chargeType;
    return this;
  }

   /**
   * Get chargeType
   * @return chargeType
  **/
  @Schema(description = "")
  public String getChargeType() {
    return chargeType;
  }

  public void setChargeType(String chargeType) {
    this.chargeType = chargeType;
  }

  public GetResourceQueueResponse computeResources(List<ComputeResourceForGetResourceQueueOutput> computeResources) {
    this.computeResources = computeResources;
    return this;
  }

  public GetResourceQueueResponse addComputeResourcesItem(ComputeResourceForGetResourceQueueOutput computeResourcesItem) {
    if (this.computeResources == null) {
      this.computeResources = new ArrayList<ComputeResourceForGetResourceQueueOutput>();
    }
    this.computeResources.add(computeResourcesItem);
    return this;
  }

   /**
   * Get computeResources
   * @return computeResources
  **/
  @Valid
  @Schema(description = "")
  public List<ComputeResourceForGetResourceQueueOutput> getComputeResources() {
    return computeResources;
  }

  public void setComputeResources(List<ComputeResourceForGetResourceQueueOutput> computeResources) {
    this.computeResources = computeResources;
  }

  public GetResourceQueueResponse description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public GetResourceQueueResponse id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public GetResourceQueueResponse name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public GetResourceQueueResponse projectName(String projectName) {
    this.projectName = projectName;
    return this;
  }

   /**
   * Get projectName
   * @return projectName
  **/
  @Schema(description = "")
  public String getProjectName() {
    return projectName;
  }

  public void setProjectName(String projectName) {
    this.projectName = projectName;
  }

  public GetResourceQueueResponse quotaAllocated(QuotaAllocatedForGetResourceQueueOutput quotaAllocated) {
    this.quotaAllocated = quotaAllocated;
    return this;
  }

   /**
   * Get quotaAllocated
   * @return quotaAllocated
  **/
  @Valid
  @Schema(description = "")
  public QuotaAllocatedForGetResourceQueueOutput getQuotaAllocated() {
    return quotaAllocated;
  }

  public void setQuotaAllocated(QuotaAllocatedForGetResourceQueueOutput quotaAllocated) {
    this.quotaAllocated = quotaAllocated;
  }

  public GetResourceQueueResponse quotaCapability(QuotaCapabilityForGetResourceQueueOutput quotaCapability) {
    this.quotaCapability = quotaCapability;
    return this;
  }

   /**
   * Get quotaCapability
   * @return quotaCapability
  **/
  @Valid
  @Schema(description = "")
  public QuotaCapabilityForGetResourceQueueOutput getQuotaCapability() {
    return quotaCapability;
  }

  public void setQuotaCapability(QuotaCapabilityForGetResourceQueueOutput quotaCapability) {
    this.quotaCapability = quotaCapability;
  }

  public GetResourceQueueResponse resourceGroupId(String resourceGroupId) {
    this.resourceGroupId = resourceGroupId;
    return this;
  }

   /**
   * Get resourceGroupId
   * @return resourceGroupId
  **/
  @Schema(description = "")
  public String getResourceGroupId() {
    return resourceGroupId;
  }

  public void setResourceGroupId(String resourceGroupId) {
    this.resourceGroupId = resourceGroupId;
  }

  public GetResourceQueueResponse rules(RulesForGetResourceQueueOutput rules) {
    this.rules = rules;
    return this;
  }

   /**
   * Get rules
   * @return rules
  **/
  @Valid
  @Schema(description = "")
  public RulesForGetResourceQueueOutput getRules() {
    return rules;
  }

  public void setRules(RulesForGetResourceQueueOutput rules) {
    this.rules = rules;
  }

  public GetResourceQueueResponse shareable(Boolean shareable) {
    this.shareable = shareable;
    return this;
  }

   /**
   * Get shareable
   * @return shareable
  **/
  @Schema(description = "")
  public Boolean isShareable() {
    return shareable;
  }

  public void setShareable(Boolean shareable) {
    this.shareable = shareable;
  }

  public GetResourceQueueResponse sharedQuotaAllocated(SharedQuotaAllocatedForGetResourceQueueOutput sharedQuotaAllocated) {
    this.sharedQuotaAllocated = sharedQuotaAllocated;
    return this;
  }

   /**
   * Get sharedQuotaAllocated
   * @return sharedQuotaAllocated
  **/
  @Valid
  @Schema(description = "")
  public SharedQuotaAllocatedForGetResourceQueueOutput getSharedQuotaAllocated() {
    return sharedQuotaAllocated;
  }

  public void setSharedQuotaAllocated(SharedQuotaAllocatedForGetResourceQueueOutput sharedQuotaAllocated) {
    this.sharedQuotaAllocated = sharedQuotaAllocated;
  }

  public GetResourceQueueResponse status(StatusForGetResourceQueueOutput status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Valid
  @Schema(description = "")
  public StatusForGetResourceQueueOutput getStatus() {
    return status;
  }

  public void setStatus(StatusForGetResourceQueueOutput status) {
    this.status = status;
  }

  public GetResourceQueueResponse systemQuotaAllocated(SystemQuotaAllocatedForGetResourceQueueOutput systemQuotaAllocated) {
    this.systemQuotaAllocated = systemQuotaAllocated;
    return this;
  }

   /**
   * Get systemQuotaAllocated
   * @return systemQuotaAllocated
  **/
  @Valid
  @Schema(description = "")
  public SystemQuotaAllocatedForGetResourceQueueOutput getSystemQuotaAllocated() {
    return systemQuotaAllocated;
  }

  public void setSystemQuotaAllocated(SystemQuotaAllocatedForGetResourceQueueOutput systemQuotaAllocated) {
    this.systemQuotaAllocated = systemQuotaAllocated;
  }

  public GetResourceQueueResponse volumeResources(List<VolumeResourceForGetResourceQueueOutput> volumeResources) {
    this.volumeResources = volumeResources;
    return this;
  }

  public GetResourceQueueResponse addVolumeResourcesItem(VolumeResourceForGetResourceQueueOutput volumeResourcesItem) {
    if (this.volumeResources == null) {
      this.volumeResources = new ArrayList<VolumeResourceForGetResourceQueueOutput>();
    }
    this.volumeResources.add(volumeResourcesItem);
    return this;
  }

   /**
   * Get volumeResources
   * @return volumeResources
  **/
  @Valid
  @Schema(description = "")
  public List<VolumeResourceForGetResourceQueueOutput> getVolumeResources() {
    return volumeResources;
  }

  public void setVolumeResources(List<VolumeResourceForGetResourceQueueOutput> volumeResources) {
    this.volumeResources = volumeResources;
  }

  public GetResourceQueueResponse workloadInfos(List<WorkloadInfoForGetResourceQueueOutput> workloadInfos) {
    this.workloadInfos = workloadInfos;
    return this;
  }

  public GetResourceQueueResponse addWorkloadInfosItem(WorkloadInfoForGetResourceQueueOutput workloadInfosItem) {
    if (this.workloadInfos == null) {
      this.workloadInfos = new ArrayList<WorkloadInfoForGetResourceQueueOutput>();
    }
    this.workloadInfos.add(workloadInfosItem);
    return this;
  }

   /**
   * Get workloadInfos
   * @return workloadInfos
  **/
  @Valid
  @Schema(description = "")
  public List<WorkloadInfoForGetResourceQueueOutput> getWorkloadInfos() {
    return workloadInfos;
  }

  public void setWorkloadInfos(List<WorkloadInfoForGetResourceQueueOutput> workloadInfos) {
    this.workloadInfos = workloadInfos;
  }

  public GetResourceQueueResponse zoneIds(List<String> zoneIds) {
    this.zoneIds = zoneIds;
    return this;
  }

  public GetResourceQueueResponse addZoneIdsItem(String zoneIdsItem) {
    if (this.zoneIds == null) {
      this.zoneIds = new ArrayList<String>();
    }
    this.zoneIds.add(zoneIdsItem);
    return this;
  }

   /**
   * Get zoneIds
   * @return zoneIds
  **/
  @Schema(description = "")
  public List<String> getZoneIds() {
    return zoneIds;
  }

  public void setZoneIds(List<String> zoneIds) {
    this.zoneIds = zoneIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetResourceQueueResponse getResourceQueueResponse = (GetResourceQueueResponse) o;
    return Objects.equals(this.chargeType, getResourceQueueResponse.chargeType) &&
        Objects.equals(this.computeResources, getResourceQueueResponse.computeResources) &&
        Objects.equals(this.description, getResourceQueueResponse.description) &&
        Objects.equals(this.id, getResourceQueueResponse.id) &&
        Objects.equals(this.name, getResourceQueueResponse.name) &&
        Objects.equals(this.projectName, getResourceQueueResponse.projectName) &&
        Objects.equals(this.quotaAllocated, getResourceQueueResponse.quotaAllocated) &&
        Objects.equals(this.quotaCapability, getResourceQueueResponse.quotaCapability) &&
        Objects.equals(this.resourceGroupId, getResourceQueueResponse.resourceGroupId) &&
        Objects.equals(this.rules, getResourceQueueResponse.rules) &&
        Objects.equals(this.shareable, getResourceQueueResponse.shareable) &&
        Objects.equals(this.sharedQuotaAllocated, getResourceQueueResponse.sharedQuotaAllocated) &&
        Objects.equals(this.status, getResourceQueueResponse.status) &&
        Objects.equals(this.systemQuotaAllocated, getResourceQueueResponse.systemQuotaAllocated) &&
        Objects.equals(this.volumeResources, getResourceQueueResponse.volumeResources) &&
        Objects.equals(this.workloadInfos, getResourceQueueResponse.workloadInfos) &&
        Objects.equals(this.zoneIds, getResourceQueueResponse.zoneIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(chargeType, computeResources, description, id, name, projectName, quotaAllocated, quotaCapability, resourceGroupId, rules, shareable, sharedQuotaAllocated, status, systemQuotaAllocated, volumeResources, workloadInfos, zoneIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetResourceQueueResponse {\n");
    
    sb.append("    chargeType: ").append(toIndentedString(chargeType)).append("\n");
    sb.append("    computeResources: ").append(toIndentedString(computeResources)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    projectName: ").append(toIndentedString(projectName)).append("\n");
    sb.append("    quotaAllocated: ").append(toIndentedString(quotaAllocated)).append("\n");
    sb.append("    quotaCapability: ").append(toIndentedString(quotaCapability)).append("\n");
    sb.append("    resourceGroupId: ").append(toIndentedString(resourceGroupId)).append("\n");
    sb.append("    rules: ").append(toIndentedString(rules)).append("\n");
    sb.append("    shareable: ").append(toIndentedString(shareable)).append("\n");
    sb.append("    sharedQuotaAllocated: ").append(toIndentedString(sharedQuotaAllocated)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    systemQuotaAllocated: ").append(toIndentedString(systemQuotaAllocated)).append("\n");
    sb.append("    volumeResources: ").append(toIndentedString(volumeResources)).append("\n");
    sb.append("    workloadInfos: ").append(toIndentedString(workloadInfos)).append("\n");
    sb.append("    zoneIds: ").append(toIndentedString(zoneIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
