/*
 * ml_platform20240701
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.volcengine.mlplatform20240701.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.volcengine.mlplatform20240701.model.StatusForListDevInstancesOutput;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * PortForListDevInstancesOutput
 */



public class PortForListDevInstancesOutput {
  @SerializedName("APIGPrivateUrl")
  private String apIGPrivateUrl = null;

  @SerializedName("APIGPublicUrl")
  private String apIGPublicUrl = null;

  @SerializedName("EnablePublicNetworkAccess")
  private Boolean enablePublicNetworkAccess = null;

  @SerializedName("EniIp")
  private String eniIp = null;

  @SerializedName("EniPort")
  private Integer eniPort = null;

  @SerializedName("ExternalIp")
  private String externalIp = null;

  @SerializedName("ExternalPort")
  private Integer externalPort = null;

  @SerializedName("Name")
  private String name = null;

  @SerializedName("Status")
  private StatusForListDevInstancesOutput status = null;

  @SerializedName("Type")
  private String type = null;

  public PortForListDevInstancesOutput apIGPrivateUrl(String apIGPrivateUrl) {
    this.apIGPrivateUrl = apIGPrivateUrl;
    return this;
  }

   /**
   * Get apIGPrivateUrl
   * @return apIGPrivateUrl
  **/
  @Schema(description = "")
  public String getApIGPrivateUrl() {
    return apIGPrivateUrl;
  }

  public void setApIGPrivateUrl(String apIGPrivateUrl) {
    this.apIGPrivateUrl = apIGPrivateUrl;
  }

  public PortForListDevInstancesOutput apIGPublicUrl(String apIGPublicUrl) {
    this.apIGPublicUrl = apIGPublicUrl;
    return this;
  }

   /**
   * Get apIGPublicUrl
   * @return apIGPublicUrl
  **/
  @Schema(description = "")
  public String getApIGPublicUrl() {
    return apIGPublicUrl;
  }

  public void setApIGPublicUrl(String apIGPublicUrl) {
    this.apIGPublicUrl = apIGPublicUrl;
  }

  public PortForListDevInstancesOutput enablePublicNetworkAccess(Boolean enablePublicNetworkAccess) {
    this.enablePublicNetworkAccess = enablePublicNetworkAccess;
    return this;
  }

   /**
   * Get enablePublicNetworkAccess
   * @return enablePublicNetworkAccess
  **/
  @Schema(description = "")
  public Boolean isEnablePublicNetworkAccess() {
    return enablePublicNetworkAccess;
  }

  public void setEnablePublicNetworkAccess(Boolean enablePublicNetworkAccess) {
    this.enablePublicNetworkAccess = enablePublicNetworkAccess;
  }

  public PortForListDevInstancesOutput eniIp(String eniIp) {
    this.eniIp = eniIp;
    return this;
  }

   /**
   * Get eniIp
   * @return eniIp
  **/
  @Schema(description = "")
  public String getEniIp() {
    return eniIp;
  }

  public void setEniIp(String eniIp) {
    this.eniIp = eniIp;
  }

  public PortForListDevInstancesOutput eniPort(Integer eniPort) {
    this.eniPort = eniPort;
    return this;
  }

   /**
   * Get eniPort
   * @return eniPort
  **/
  @Schema(description = "")
  public Integer getEniPort() {
    return eniPort;
  }

  public void setEniPort(Integer eniPort) {
    this.eniPort = eniPort;
  }

  public PortForListDevInstancesOutput externalIp(String externalIp) {
    this.externalIp = externalIp;
    return this;
  }

   /**
   * Get externalIp
   * @return externalIp
  **/
  @Schema(description = "")
  public String getExternalIp() {
    return externalIp;
  }

  public void setExternalIp(String externalIp) {
    this.externalIp = externalIp;
  }

  public PortForListDevInstancesOutput externalPort(Integer externalPort) {
    this.externalPort = externalPort;
    return this;
  }

   /**
   * Get externalPort
   * @return externalPort
  **/
  @Schema(description = "")
  public Integer getExternalPort() {
    return externalPort;
  }

  public void setExternalPort(Integer externalPort) {
    this.externalPort = externalPort;
  }

  public PortForListDevInstancesOutput name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public PortForListDevInstancesOutput status(StatusForListDevInstancesOutput status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Valid
  @Schema(description = "")
  public StatusForListDevInstancesOutput getStatus() {
    return status;
  }

  public void setStatus(StatusForListDevInstancesOutput status) {
    this.status = status;
  }

  public PortForListDevInstancesOutput type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema(description = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PortForListDevInstancesOutput portForListDevInstancesOutput = (PortForListDevInstancesOutput) o;
    return Objects.equals(this.apIGPrivateUrl, portForListDevInstancesOutput.apIGPrivateUrl) &&
        Objects.equals(this.apIGPublicUrl, portForListDevInstancesOutput.apIGPublicUrl) &&
        Objects.equals(this.enablePublicNetworkAccess, portForListDevInstancesOutput.enablePublicNetworkAccess) &&
        Objects.equals(this.eniIp, portForListDevInstancesOutput.eniIp) &&
        Objects.equals(this.eniPort, portForListDevInstancesOutput.eniPort) &&
        Objects.equals(this.externalIp, portForListDevInstancesOutput.externalIp) &&
        Objects.equals(this.externalPort, portForListDevInstancesOutput.externalPort) &&
        Objects.equals(this.name, portForListDevInstancesOutput.name) &&
        Objects.equals(this.status, portForListDevInstancesOutput.status) &&
        Objects.equals(this.type, portForListDevInstancesOutput.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(apIGPrivateUrl, apIGPublicUrl, enablePublicNetworkAccess, eniIp, eniPort, externalIp, externalPort, name, status, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PortForListDevInstancesOutput {\n");
    
    sb.append("    apIGPrivateUrl: ").append(toIndentedString(apIGPrivateUrl)).append("\n");
    sb.append("    apIGPublicUrl: ").append(toIndentedString(apIGPublicUrl)).append("\n");
    sb.append("    enablePublicNetworkAccess: ").append(toIndentedString(enablePublicNetworkAccess)).append("\n");
    sb.append("    eniIp: ").append(toIndentedString(eniIp)).append("\n");
    sb.append("    eniPort: ").append(toIndentedString(eniPort)).append("\n");
    sb.append("    externalIp: ").append(toIndentedString(externalIp)).append("\n");
    sb.append("    externalPort: ").append(toIndentedString(externalPort)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
