/*
 * ml_platform20240701
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.volcengine.mlplatform20240701.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.volcengine.mlplatform20240701.model.StorageNetworkConfigForUpdateResourceReservationPlanInput;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * StorageConfigForUpdateResourceReservationPlanInput
 */



public class StorageConfigForUpdateResourceReservationPlanInput {
  @SerializedName("StorageNetworkConfig")
  private StorageNetworkConfigForUpdateResourceReservationPlanInput storageNetworkConfig = null;

  public StorageConfigForUpdateResourceReservationPlanInput storageNetworkConfig(StorageNetworkConfigForUpdateResourceReservationPlanInput storageNetworkConfig) {
    this.storageNetworkConfig = storageNetworkConfig;
    return this;
  }

   /**
   * Get storageNetworkConfig
   * @return storageNetworkConfig
  **/
  @Valid
  @Schema(description = "")
  public StorageNetworkConfigForUpdateResourceReservationPlanInput getStorageNetworkConfig() {
    return storageNetworkConfig;
  }

  public void setStorageNetworkConfig(StorageNetworkConfigForUpdateResourceReservationPlanInput storageNetworkConfig) {
    this.storageNetworkConfig = storageNetworkConfig;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StorageConfigForUpdateResourceReservationPlanInput storageConfigForUpdateResourceReservationPlanInput = (StorageConfigForUpdateResourceReservationPlanInput) o;
    return Objects.equals(this.storageNetworkConfig, storageConfigForUpdateResourceReservationPlanInput.storageNetworkConfig);
  }

  @Override
  public int hashCode() {
    return Objects.hash(storageNetworkConfig);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StorageConfigForUpdateResourceReservationPlanInput {\n");
    
    sb.append("    storageNetworkConfig: ").append(toIndentedString(storageNetworkConfig)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
