/*
 * dbw
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.volcengine.dbw.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.volcengine.dbw.model.CreateUserForDescribeTicketsOutput;
import com.volcengine.dbw.model.CurrentUserForDescribeTicketsOutput;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * TicketForDescribeTicketsOutput
 */



public class TicketForDescribeTicketsOutput {
  @SerializedName("CreateTime")
  private String createTime = null;

  @SerializedName("CreateUser")
  private CreateUserForDescribeTicketsOutput createUser = null;

  @SerializedName("CurrentUser")
  private CurrentUserForDescribeTicketsOutput currentUser = null;

  @SerializedName("CurrentUserRole")
  private String currentUserRole = null;

  @SerializedName("DBName")
  private String dbName = null;

  @SerializedName("InstanceId")
  private String instanceId = null;

  @SerializedName("InstanceType")
  private String instanceType = null;

  @SerializedName("Memo")
  private String memo = null;

  @SerializedName("TicketExecuteType")
  private String ticketExecuteType = null;

  @SerializedName("TicketId")
  private String ticketId = null;

  @SerializedName("TicketStatus")
  private String ticketStatus = null;

  @SerializedName("TicketType")
  private String ticketType = null;

  @SerializedName("Title")
  private String title = null;

  @SerializedName("UpdateTime")
  private String updateTime = null;

  public TicketForDescribeTicketsOutput createTime(String createTime) {
    this.createTime = createTime;
    return this;
  }

   /**
   * Get createTime
   * @return createTime
  **/
  @Schema(description = "")
  public String getCreateTime() {
    return createTime;
  }

  public void setCreateTime(String createTime) {
    this.createTime = createTime;
  }

  public TicketForDescribeTicketsOutput createUser(CreateUserForDescribeTicketsOutput createUser) {
    this.createUser = createUser;
    return this;
  }

   /**
   * Get createUser
   * @return createUser
  **/
  @Valid
  @Schema(description = "")
  public CreateUserForDescribeTicketsOutput getCreateUser() {
    return createUser;
  }

  public void setCreateUser(CreateUserForDescribeTicketsOutput createUser) {
    this.createUser = createUser;
  }

  public TicketForDescribeTicketsOutput currentUser(CurrentUserForDescribeTicketsOutput currentUser) {
    this.currentUser = currentUser;
    return this;
  }

   /**
   * Get currentUser
   * @return currentUser
  **/
  @Valid
  @Schema(description = "")
  public CurrentUserForDescribeTicketsOutput getCurrentUser() {
    return currentUser;
  }

  public void setCurrentUser(CurrentUserForDescribeTicketsOutput currentUser) {
    this.currentUser = currentUser;
  }

  public TicketForDescribeTicketsOutput currentUserRole(String currentUserRole) {
    this.currentUserRole = currentUserRole;
    return this;
  }

   /**
   * Get currentUserRole
   * @return currentUserRole
  **/
  @Schema(description = "")
  public String getCurrentUserRole() {
    return currentUserRole;
  }

  public void setCurrentUserRole(String currentUserRole) {
    this.currentUserRole = currentUserRole;
  }

  public TicketForDescribeTicketsOutput dbName(String dbName) {
    this.dbName = dbName;
    return this;
  }

   /**
   * Get dbName
   * @return dbName
  **/
  @Schema(description = "")
  public String getDbName() {
    return dbName;
  }

  public void setDbName(String dbName) {
    this.dbName = dbName;
  }

  public TicketForDescribeTicketsOutput instanceId(String instanceId) {
    this.instanceId = instanceId;
    return this;
  }

   /**
   * Get instanceId
   * @return instanceId
  **/
  @Schema(description = "")
  public String getInstanceId() {
    return instanceId;
  }

  public void setInstanceId(String instanceId) {
    this.instanceId = instanceId;
  }

  public TicketForDescribeTicketsOutput instanceType(String instanceType) {
    this.instanceType = instanceType;
    return this;
  }

   /**
   * Get instanceType
   * @return instanceType
  **/
  @Schema(description = "")
  public String getInstanceType() {
    return instanceType;
  }

  public void setInstanceType(String instanceType) {
    this.instanceType = instanceType;
  }

  public TicketForDescribeTicketsOutput memo(String memo) {
    this.memo = memo;
    return this;
  }

   /**
   * Get memo
   * @return memo
  **/
  @Schema(description = "")
  public String getMemo() {
    return memo;
  }

  public void setMemo(String memo) {
    this.memo = memo;
  }

  public TicketForDescribeTicketsOutput ticketExecuteType(String ticketExecuteType) {
    this.ticketExecuteType = ticketExecuteType;
    return this;
  }

   /**
   * Get ticketExecuteType
   * @return ticketExecuteType
  **/
  @Schema(description = "")
  public String getTicketExecuteType() {
    return ticketExecuteType;
  }

  public void setTicketExecuteType(String ticketExecuteType) {
    this.ticketExecuteType = ticketExecuteType;
  }

  public TicketForDescribeTicketsOutput ticketId(String ticketId) {
    this.ticketId = ticketId;
    return this;
  }

   /**
   * Get ticketId
   * @return ticketId
  **/
  @Schema(description = "")
  public String getTicketId() {
    return ticketId;
  }

  public void setTicketId(String ticketId) {
    this.ticketId = ticketId;
  }

  public TicketForDescribeTicketsOutput ticketStatus(String ticketStatus) {
    this.ticketStatus = ticketStatus;
    return this;
  }

   /**
   * Get ticketStatus
   * @return ticketStatus
  **/
  @Schema(description = "")
  public String getTicketStatus() {
    return ticketStatus;
  }

  public void setTicketStatus(String ticketStatus) {
    this.ticketStatus = ticketStatus;
  }

  public TicketForDescribeTicketsOutput ticketType(String ticketType) {
    this.ticketType = ticketType;
    return this;
  }

   /**
   * Get ticketType
   * @return ticketType
  **/
  @Schema(description = "")
  public String getTicketType() {
    return ticketType;
  }

  public void setTicketType(String ticketType) {
    this.ticketType = ticketType;
  }

  public TicketForDescribeTicketsOutput title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @Schema(description = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public TicketForDescribeTicketsOutput updateTime(String updateTime) {
    this.updateTime = updateTime;
    return this;
  }

   /**
   * Get updateTime
   * @return updateTime
  **/
  @Schema(description = "")
  public String getUpdateTime() {
    return updateTime;
  }

  public void setUpdateTime(String updateTime) {
    this.updateTime = updateTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TicketForDescribeTicketsOutput ticketForDescribeTicketsOutput = (TicketForDescribeTicketsOutput) o;
    return Objects.equals(this.createTime, ticketForDescribeTicketsOutput.createTime) &&
        Objects.equals(this.createUser, ticketForDescribeTicketsOutput.createUser) &&
        Objects.equals(this.currentUser, ticketForDescribeTicketsOutput.currentUser) &&
        Objects.equals(this.currentUserRole, ticketForDescribeTicketsOutput.currentUserRole) &&
        Objects.equals(this.dbName, ticketForDescribeTicketsOutput.dbName) &&
        Objects.equals(this.instanceId, ticketForDescribeTicketsOutput.instanceId) &&
        Objects.equals(this.instanceType, ticketForDescribeTicketsOutput.instanceType) &&
        Objects.equals(this.memo, ticketForDescribeTicketsOutput.memo) &&
        Objects.equals(this.ticketExecuteType, ticketForDescribeTicketsOutput.ticketExecuteType) &&
        Objects.equals(this.ticketId, ticketForDescribeTicketsOutput.ticketId) &&
        Objects.equals(this.ticketStatus, ticketForDescribeTicketsOutput.ticketStatus) &&
        Objects.equals(this.ticketType, ticketForDescribeTicketsOutput.ticketType) &&
        Objects.equals(this.title, ticketForDescribeTicketsOutput.title) &&
        Objects.equals(this.updateTime, ticketForDescribeTicketsOutput.updateTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createTime, createUser, currentUser, currentUserRole, dbName, instanceId, instanceType, memo, ticketExecuteType, ticketId, ticketStatus, ticketType, title, updateTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TicketForDescribeTicketsOutput {\n");
    
    sb.append("    createTime: ").append(toIndentedString(createTime)).append("\n");
    sb.append("    createUser: ").append(toIndentedString(createUser)).append("\n");
    sb.append("    currentUser: ").append(toIndentedString(currentUser)).append("\n");
    sb.append("    currentUserRole: ").append(toIndentedString(currentUserRole)).append("\n");
    sb.append("    dbName: ").append(toIndentedString(dbName)).append("\n");
    sb.append("    instanceId: ").append(toIndentedString(instanceId)).append("\n");
    sb.append("    instanceType: ").append(toIndentedString(instanceType)).append("\n");
    sb.append("    memo: ").append(toIndentedString(memo)).append("\n");
    sb.append("    ticketExecuteType: ").append(toIndentedString(ticketExecuteType)).append("\n");
    sb.append("    ticketId: ").append(toIndentedString(ticketId)).append("\n");
    sb.append("    ticketStatus: ").append(toIndentedString(ticketStatus)).append("\n");
    sb.append("    ticketType: ").append(toIndentedString(ticketType)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    updateTime: ").append(toIndentedString(updateTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
