/*
 * cdn
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.volcengine.cdn.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * DescribeCertConfigRequest
 */



public class DescribeCertConfigRequest {
  @SerializedName("CertId")
  private String certId = null;

  @SerializedName("CertId2")
  private String certId2 = null;

  @SerializedName("CertType")
  private String certType = null;

  @SerializedName("EncryType")
  private String encryType = null;

  @SerializedName("Status")
  private String status = null;

  public DescribeCertConfigRequest certId(String certId) {
    this.certId = certId;
    return this;
  }

   /**
   * Get certId
   * @return certId
  **/
  @NotNull
  @Schema(required = true, description = "")
  public String getCertId() {
    return certId;
  }

  public void setCertId(String certId) {
    this.certId = certId;
  }

  public DescribeCertConfigRequest certId2(String certId2) {
    this.certId2 = certId2;
    return this;
  }

   /**
   * Get certId2
   * @return certId2
  **/
  @Schema(description = "")
  public String getCertId2() {
    return certId2;
  }

  public void setCertId2(String certId2) {
    this.certId2 = certId2;
  }

  public DescribeCertConfigRequest certType(String certType) {
    this.certType = certType;
    return this;
  }

   /**
   * Get certType
   * @return certType
  **/
  @Schema(description = "")
  public String getCertType() {
    return certType;
  }

  public void setCertType(String certType) {
    this.certType = certType;
  }

  public DescribeCertConfigRequest encryType(String encryType) {
    this.encryType = encryType;
    return this;
  }

   /**
   * Get encryType
   * @return encryType
  **/
  @Schema(description = "")
  public String getEncryType() {
    return encryType;
  }

  public void setEncryType(String encryType) {
    this.encryType = encryType;
  }

  public DescribeCertConfigRequest status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(description = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DescribeCertConfigRequest describeCertConfigRequest = (DescribeCertConfigRequest) o;
    return Objects.equals(this.certId, describeCertConfigRequest.certId) &&
        Objects.equals(this.certId2, describeCertConfigRequest.certId2) &&
        Objects.equals(this.certType, describeCertConfigRequest.certType) &&
        Objects.equals(this.encryType, describeCertConfigRequest.encryType) &&
        Objects.equals(this.status, describeCertConfigRequest.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(certId, certId2, certType, encryType, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DescribeCertConfigRequest {\n");
    
    sb.append("    certId: ").append(toIndentedString(certId)).append("\n");
    sb.append("    certId2: ").append(toIndentedString(certId2)).append("\n");
    sb.append("    certType: ").append(toIndentedString(certType)).append("\n");
    sb.append("    encryType: ").append(toIndentedString(encryType)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
