/*
 * i18n_openapi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.volcengine.i18nopenapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * DataForVideoEditorDownloadSubtitleFileUrlOutput
 */



public class DataForVideoEditorDownloadSubtitleFileUrlOutput {
  @SerializedName("filename")
  private String filename = null;

  @SerializedName("url")
  private String url = null;

  public DataForVideoEditorDownloadSubtitleFileUrlOutput filename(String filename) {
    this.filename = filename;
    return this;
  }

   /**
   * Get filename
   * @return filename
  **/
  @Schema(description = "")
  public String getFilename() {
    return filename;
  }

  public void setFilename(String filename) {
    this.filename = filename;
  }

  public DataForVideoEditorDownloadSubtitleFileUrlOutput url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @Schema(description = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DataForVideoEditorDownloadSubtitleFileUrlOutput dataForVideoEditorDownloadSubtitleFileUrlOutput = (DataForVideoEditorDownloadSubtitleFileUrlOutput) o;
    return Objects.equals(this.filename, dataForVideoEditorDownloadSubtitleFileUrlOutput.filename) &&
        Objects.equals(this.url, dataForVideoEditorDownloadSubtitleFileUrlOutput.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(filename, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DataForVideoEditorDownloadSubtitleFileUrlOutput {\n");
    
    sb.append("    filename: ").append(toIndentedString(filename)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
