/*
 * i18n_openapi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.volcengine.i18nopenapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * ProjectNamespaceSourceDetailRequest
 */



public class ProjectNamespaceSourceDetailRequest {
  @SerializedName("keyText")
  private String keyText = null;

  @SerializedName("locale")
  private String locale = null;

  @SerializedName("namespaceId")
  private Integer namespaceId = null;

  @SerializedName("projectId")
  private Integer projectId = null;

  public ProjectNamespaceSourceDetailRequest keyText(String keyText) {
    this.keyText = keyText;
    return this;
  }

   /**
   * Get keyText
   * @return keyText
  **/
  @NotNull
  @Schema(required = true, description = "")
  public String getKeyText() {
    return keyText;
  }

  public void setKeyText(String keyText) {
    this.keyText = keyText;
  }

  public ProjectNamespaceSourceDetailRequest locale(String locale) {
    this.locale = locale;
    return this;
  }

   /**
   * Get locale
   * @return locale
  **/
  @Schema(description = "")
  public String getLocale() {
    return locale;
  }

  public void setLocale(String locale) {
    this.locale = locale;
  }

  public ProjectNamespaceSourceDetailRequest namespaceId(Integer namespaceId) {
    this.namespaceId = namespaceId;
    return this;
  }

   /**
   * Get namespaceId
   * @return namespaceId
  **/
  @NotNull
  @Schema(required = true, description = "")
  public Integer getNamespaceId() {
    return namespaceId;
  }

  public void setNamespaceId(Integer namespaceId) {
    this.namespaceId = namespaceId;
  }

  public ProjectNamespaceSourceDetailRequest projectId(Integer projectId) {
    this.projectId = projectId;
    return this;
  }

   /**
   * Get projectId
   * @return projectId
  **/
  @NotNull
  @Schema(required = true, description = "")
  public Integer getProjectId() {
    return projectId;
  }

  public void setProjectId(Integer projectId) {
    this.projectId = projectId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProjectNamespaceSourceDetailRequest projectNamespaceSourceDetailRequest = (ProjectNamespaceSourceDetailRequest) o;
    return Objects.equals(this.keyText, projectNamespaceSourceDetailRequest.keyText) &&
        Objects.equals(this.locale, projectNamespaceSourceDetailRequest.locale) &&
        Objects.equals(this.namespaceId, projectNamespaceSourceDetailRequest.namespaceId) &&
        Objects.equals(this.projectId, projectNamespaceSourceDetailRequest.projectId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(keyText, locale, namespaceId, projectId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProjectNamespaceSourceDetailRequest {\n");
    
    sb.append("    keyText: ").append(toIndentedString(keyText)).append("\n");
    sb.append("    locale: ").append(toIndentedString(locale)).append("\n");
    sb.append("    namespaceId: ").append(toIndentedString(namespaceId)).append("\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
