/*
 * i18n_openapi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.volcengine.i18nopenapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.volcengine.i18nopenapi.model.InputVideoInfoForVideoProjectListToolTaskByResourceIDsOutput;
import com.volcengine.i18nopenapi.model.OutputVideoInfoForVideoProjectListToolTaskByResourceIDsOutput;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * ToolTaskResultForVideoProjectListToolTaskByResourceIDsOutput
 */



public class ToolTaskResultForVideoProjectListToolTaskByResourceIDsOutput {
  @SerializedName("episodeNum")
  private String episodeNum = null;

  @SerializedName("inputVid")
  private String inputVid = null;

  @SerializedName("inputVideoInfo")
  private InputVideoInfoForVideoProjectListToolTaskByResourceIDsOutput inputVideoInfo = null;

  @SerializedName("outputVid")
  private String outputVid = null;

  @SerializedName("outputVideoInfo")
  private OutputVideoInfoForVideoProjectListToolTaskByResourceIDsOutput outputVideoInfo = null;

  public ToolTaskResultForVideoProjectListToolTaskByResourceIDsOutput episodeNum(String episodeNum) {
    this.episodeNum = episodeNum;
    return this;
  }

   /**
   * Get episodeNum
   * @return episodeNum
  **/
  @Schema(description = "")
  public String getEpisodeNum() {
    return episodeNum;
  }

  public void setEpisodeNum(String episodeNum) {
    this.episodeNum = episodeNum;
  }

  public ToolTaskResultForVideoProjectListToolTaskByResourceIDsOutput inputVid(String inputVid) {
    this.inputVid = inputVid;
    return this;
  }

   /**
   * Get inputVid
   * @return inputVid
  **/
  @Schema(description = "")
  public String getInputVid() {
    return inputVid;
  }

  public void setInputVid(String inputVid) {
    this.inputVid = inputVid;
  }

  public ToolTaskResultForVideoProjectListToolTaskByResourceIDsOutput inputVideoInfo(InputVideoInfoForVideoProjectListToolTaskByResourceIDsOutput inputVideoInfo) {
    this.inputVideoInfo = inputVideoInfo;
    return this;
  }

   /**
   * Get inputVideoInfo
   * @return inputVideoInfo
  **/
  @Valid
  @Schema(description = "")
  public InputVideoInfoForVideoProjectListToolTaskByResourceIDsOutput getInputVideoInfo() {
    return inputVideoInfo;
  }

  public void setInputVideoInfo(InputVideoInfoForVideoProjectListToolTaskByResourceIDsOutput inputVideoInfo) {
    this.inputVideoInfo = inputVideoInfo;
  }

  public ToolTaskResultForVideoProjectListToolTaskByResourceIDsOutput outputVid(String outputVid) {
    this.outputVid = outputVid;
    return this;
  }

   /**
   * Get outputVid
   * @return outputVid
  **/
  @Schema(description = "")
  public String getOutputVid() {
    return outputVid;
  }

  public void setOutputVid(String outputVid) {
    this.outputVid = outputVid;
  }

  public ToolTaskResultForVideoProjectListToolTaskByResourceIDsOutput outputVideoInfo(OutputVideoInfoForVideoProjectListToolTaskByResourceIDsOutput outputVideoInfo) {
    this.outputVideoInfo = outputVideoInfo;
    return this;
  }

   /**
   * Get outputVideoInfo
   * @return outputVideoInfo
  **/
  @Valid
  @Schema(description = "")
  public OutputVideoInfoForVideoProjectListToolTaskByResourceIDsOutput getOutputVideoInfo() {
    return outputVideoInfo;
  }

  public void setOutputVideoInfo(OutputVideoInfoForVideoProjectListToolTaskByResourceIDsOutput outputVideoInfo) {
    this.outputVideoInfo = outputVideoInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ToolTaskResultForVideoProjectListToolTaskByResourceIDsOutput toolTaskResultForVideoProjectListToolTaskByResourceIDsOutput = (ToolTaskResultForVideoProjectListToolTaskByResourceIDsOutput) o;
    return Objects.equals(this.episodeNum, toolTaskResultForVideoProjectListToolTaskByResourceIDsOutput.episodeNum) &&
        Objects.equals(this.inputVid, toolTaskResultForVideoProjectListToolTaskByResourceIDsOutput.inputVid) &&
        Objects.equals(this.inputVideoInfo, toolTaskResultForVideoProjectListToolTaskByResourceIDsOutput.inputVideoInfo) &&
        Objects.equals(this.outputVid, toolTaskResultForVideoProjectListToolTaskByResourceIDsOutput.outputVid) &&
        Objects.equals(this.outputVideoInfo, toolTaskResultForVideoProjectListToolTaskByResourceIDsOutput.outputVideoInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(episodeNum, inputVid, inputVideoInfo, outputVid, outputVideoInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ToolTaskResultForVideoProjectListToolTaskByResourceIDsOutput {\n");
    
    sb.append("    episodeNum: ").append(toIndentedString(episodeNum)).append("\n");
    sb.append("    inputVid: ").append(toIndentedString(inputVid)).append("\n");
    sb.append("    inputVideoInfo: ").append(toIndentedString(inputVideoInfo)).append("\n");
    sb.append("    outputVid: ").append(toIndentedString(outputVid)).append("\n");
    sb.append("    outputVideoInfo: ").append(toIndentedString(outputVideoInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
