/*
 * directconnect
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.volcengine.directconnect.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.volcengine.directconnect.model.DirectConnectGatewayAssociationForDescribeDirectConnectGatewayAssociationsOutput;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * DescribeDirectConnectGatewayAssociationsResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-03-24T18:20:58.026076+08:00[Asia/Shanghai]")
public class DescribeDirectConnectGatewayAssociationsResponse {
  @SerializedName("DirectConnectGatewayAssociations")
  private List<DirectConnectGatewayAssociationForDescribeDirectConnectGatewayAssociationsOutput> directConnectGatewayAssociations = null;

  @SerializedName("PageNumber")
  private Integer pageNumber = null;

  @SerializedName("PageSize")
  private Integer pageSize = null;

  @SerializedName("RequestId")
  private String requestId = null;

  @SerializedName("TotalCount")
  private Integer totalCount = null;

  public DescribeDirectConnectGatewayAssociationsResponse directConnectGatewayAssociations(List<DirectConnectGatewayAssociationForDescribeDirectConnectGatewayAssociationsOutput> directConnectGatewayAssociations) {
    this.directConnectGatewayAssociations = directConnectGatewayAssociations;
    return this;
  }

  public DescribeDirectConnectGatewayAssociationsResponse addDirectConnectGatewayAssociationsItem(DirectConnectGatewayAssociationForDescribeDirectConnectGatewayAssociationsOutput directConnectGatewayAssociationsItem) {
    if (this.directConnectGatewayAssociations == null) {
      this.directConnectGatewayAssociations = new ArrayList<DirectConnectGatewayAssociationForDescribeDirectConnectGatewayAssociationsOutput>();
    }
    this.directConnectGatewayAssociations.add(directConnectGatewayAssociationsItem);
    return this;
  }

   /**
   * Get directConnectGatewayAssociations
   * @return directConnectGatewayAssociations
  **/
  @Valid
  @Schema(description = "")
  public List<DirectConnectGatewayAssociationForDescribeDirectConnectGatewayAssociationsOutput> getDirectConnectGatewayAssociations() {
    return directConnectGatewayAssociations;
  }

  public void setDirectConnectGatewayAssociations(List<DirectConnectGatewayAssociationForDescribeDirectConnectGatewayAssociationsOutput> directConnectGatewayAssociations) {
    this.directConnectGatewayAssociations = directConnectGatewayAssociations;
  }

  public DescribeDirectConnectGatewayAssociationsResponse pageNumber(Integer pageNumber) {
    this.pageNumber = pageNumber;
    return this;
  }

   /**
   * Get pageNumber
   * @return pageNumber
  **/
  @Schema(description = "")
  public Integer getPageNumber() {
    return pageNumber;
  }

  public void setPageNumber(Integer pageNumber) {
    this.pageNumber = pageNumber;
  }

  public DescribeDirectConnectGatewayAssociationsResponse pageSize(Integer pageSize) {
    this.pageSize = pageSize;
    return this;
  }

   /**
   * Get pageSize
   * @return pageSize
  **/
  @Schema(description = "")
  public Integer getPageSize() {
    return pageSize;
  }

  public void setPageSize(Integer pageSize) {
    this.pageSize = pageSize;
  }

  public DescribeDirectConnectGatewayAssociationsResponse requestId(String requestId) {
    this.requestId = requestId;
    return this;
  }

   /**
   * Get requestId
   * @return requestId
  **/
  @Schema(description = "")
  public String getRequestId() {
    return requestId;
  }

  public void setRequestId(String requestId) {
    this.requestId = requestId;
  }

  public DescribeDirectConnectGatewayAssociationsResponse totalCount(Integer totalCount) {
    this.totalCount = totalCount;
    return this;
  }

   /**
   * Get totalCount
   * @return totalCount
  **/
  @Schema(description = "")
  public Integer getTotalCount() {
    return totalCount;
  }

  public void setTotalCount(Integer totalCount) {
    this.totalCount = totalCount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DescribeDirectConnectGatewayAssociationsResponse describeDirectConnectGatewayAssociationsResponse = (DescribeDirectConnectGatewayAssociationsResponse) o;
    return Objects.equals(this.directConnectGatewayAssociations, describeDirectConnectGatewayAssociationsResponse.directConnectGatewayAssociations) &&
        Objects.equals(this.pageNumber, describeDirectConnectGatewayAssociationsResponse.pageNumber) &&
        Objects.equals(this.pageSize, describeDirectConnectGatewayAssociationsResponse.pageSize) &&
        Objects.equals(this.requestId, describeDirectConnectGatewayAssociationsResponse.requestId) &&
        Objects.equals(this.totalCount, describeDirectConnectGatewayAssociationsResponse.totalCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(directConnectGatewayAssociations, pageNumber, pageSize, requestId, totalCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DescribeDirectConnectGatewayAssociationsResponse {\n");
    
    sb.append("    directConnectGatewayAssociations: ").append(toIndentedString(directConnectGatewayAssociations)).append("\n");
    sb.append("    pageNumber: ").append(toIndentedString(pageNumber)).append("\n");
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("    totalCount: ").append(toIndentedString(totalCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
