/*
 * rocketmq
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.volcengine.rocketmq.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.volcengine.rocketmq.model.ChargeDetailForDescribeInstancesOutput;
import com.volcengine.rocketmq.model.InstanceTagForDescribeInstancesOutput;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * InstancesInfoForDescribeInstancesOutput
 */



public class InstancesInfoForDescribeInstancesOutput {
  @SerializedName("AccountId")
  private String accountId = null;

  @SerializedName("ApplyPrivateDNSToPublic")
  private Boolean applyPrivateDNSToPublic = null;

  @SerializedName("AvailableQueueNumber")
  private Integer availableQueueNumber = null;

  @SerializedName("ChargeDetail")
  private ChargeDetailForDescribeInstancesOutput chargeDetail = null;

  @SerializedName("ComputeSpec")
  private String computeSpec = null;

  @SerializedName("CreateTime")
  private String createTime = null;

  @SerializedName("EipId")
  private String eipId = null;

  @SerializedName("EnableSSL")
  private Boolean enableSSL = null;

  @SerializedName("FileReservedTime")
  private Integer fileReservedTime = null;

  @SerializedName("InstanceDescription")
  private String instanceDescription = null;

  @SerializedName("InstanceId")
  private String instanceId = null;

  @SerializedName("InstanceName")
  private String instanceName = null;

  @SerializedName("InstanceStatus")
  private String instanceStatus = null;

  @SerializedName("InstanceTags")
  private List<InstanceTagForDescribeInstancesOutput> instanceTags = null;

  @SerializedName("ProjectName")
  private String projectName = null;

  @SerializedName("RegionId")
  private String regionId = null;

  @SerializedName("SSLMode")
  private String ssLMode = null;

  @SerializedName("StorageSpace")
  private Integer storageSpace = null;

  @SerializedName("SubnetId")
  private String subnetId = null;

  @SerializedName("UsedGroupNumber")
  private Integer usedGroupNumber = null;

  @SerializedName("UsedQueueNumber")
  private Integer usedQueueNumber = null;

  @SerializedName("UsedStorageSpace")
  private Integer usedStorageSpace = null;

  @SerializedName("UsedTopicNumber")
  private Integer usedTopicNumber = null;

  @SerializedName("Version")
  private String version = null;

  @SerializedName("VpcId")
  private String vpcId = null;

  @SerializedName("ZoneId")
  private String zoneId = null;

  public InstancesInfoForDescribeInstancesOutput accountId(String accountId) {
    this.accountId = accountId;
    return this;
  }

   /**
   * Get accountId
   * @return accountId
  **/
  @Schema(description = "")
  public String getAccountId() {
    return accountId;
  }

  public void setAccountId(String accountId) {
    this.accountId = accountId;
  }

  public InstancesInfoForDescribeInstancesOutput applyPrivateDNSToPublic(Boolean applyPrivateDNSToPublic) {
    this.applyPrivateDNSToPublic = applyPrivateDNSToPublic;
    return this;
  }

   /**
   * Get applyPrivateDNSToPublic
   * @return applyPrivateDNSToPublic
  **/
  @Schema(description = "")
  public Boolean isApplyPrivateDNSToPublic() {
    return applyPrivateDNSToPublic;
  }

  public void setApplyPrivateDNSToPublic(Boolean applyPrivateDNSToPublic) {
    this.applyPrivateDNSToPublic = applyPrivateDNSToPublic;
  }

  public InstancesInfoForDescribeInstancesOutput availableQueueNumber(Integer availableQueueNumber) {
    this.availableQueueNumber = availableQueueNumber;
    return this;
  }

   /**
   * Get availableQueueNumber
   * @return availableQueueNumber
  **/
  @Schema(description = "")
  public Integer getAvailableQueueNumber() {
    return availableQueueNumber;
  }

  public void setAvailableQueueNumber(Integer availableQueueNumber) {
    this.availableQueueNumber = availableQueueNumber;
  }

  public InstancesInfoForDescribeInstancesOutput chargeDetail(ChargeDetailForDescribeInstancesOutput chargeDetail) {
    this.chargeDetail = chargeDetail;
    return this;
  }

   /**
   * Get chargeDetail
   * @return chargeDetail
  **/
  @Valid
  @Schema(description = "")
  public ChargeDetailForDescribeInstancesOutput getChargeDetail() {
    return chargeDetail;
  }

  public void setChargeDetail(ChargeDetailForDescribeInstancesOutput chargeDetail) {
    this.chargeDetail = chargeDetail;
  }

  public InstancesInfoForDescribeInstancesOutput computeSpec(String computeSpec) {
    this.computeSpec = computeSpec;
    return this;
  }

   /**
   * Get computeSpec
   * @return computeSpec
  **/
  @Schema(description = "")
  public String getComputeSpec() {
    return computeSpec;
  }

  public void setComputeSpec(String computeSpec) {
    this.computeSpec = computeSpec;
  }

  public InstancesInfoForDescribeInstancesOutput createTime(String createTime) {
    this.createTime = createTime;
    return this;
  }

   /**
   * Get createTime
   * @return createTime
  **/
  @Schema(description = "")
  public String getCreateTime() {
    return createTime;
  }

  public void setCreateTime(String createTime) {
    this.createTime = createTime;
  }

  public InstancesInfoForDescribeInstancesOutput eipId(String eipId) {
    this.eipId = eipId;
    return this;
  }

   /**
   * Get eipId
   * @return eipId
  **/
  @Schema(description = "")
  public String getEipId() {
    return eipId;
  }

  public void setEipId(String eipId) {
    this.eipId = eipId;
  }

  public InstancesInfoForDescribeInstancesOutput enableSSL(Boolean enableSSL) {
    this.enableSSL = enableSSL;
    return this;
  }

   /**
   * Get enableSSL
   * @return enableSSL
  **/
  @Schema(description = "")
  public Boolean isEnableSSL() {
    return enableSSL;
  }

  public void setEnableSSL(Boolean enableSSL) {
    this.enableSSL = enableSSL;
  }

  public InstancesInfoForDescribeInstancesOutput fileReservedTime(Integer fileReservedTime) {
    this.fileReservedTime = fileReservedTime;
    return this;
  }

   /**
   * Get fileReservedTime
   * @return fileReservedTime
  **/
  @Schema(description = "")
  public Integer getFileReservedTime() {
    return fileReservedTime;
  }

  public void setFileReservedTime(Integer fileReservedTime) {
    this.fileReservedTime = fileReservedTime;
  }

  public InstancesInfoForDescribeInstancesOutput instanceDescription(String instanceDescription) {
    this.instanceDescription = instanceDescription;
    return this;
  }

   /**
   * Get instanceDescription
   * @return instanceDescription
  **/
  @Schema(description = "")
  public String getInstanceDescription() {
    return instanceDescription;
  }

  public void setInstanceDescription(String instanceDescription) {
    this.instanceDescription = instanceDescription;
  }

  public InstancesInfoForDescribeInstancesOutput instanceId(String instanceId) {
    this.instanceId = instanceId;
    return this;
  }

   /**
   * Get instanceId
   * @return instanceId
  **/
  @Schema(description = "")
  public String getInstanceId() {
    return instanceId;
  }

  public void setInstanceId(String instanceId) {
    this.instanceId = instanceId;
  }

  public InstancesInfoForDescribeInstancesOutput instanceName(String instanceName) {
    this.instanceName = instanceName;
    return this;
  }

   /**
   * Get instanceName
   * @return instanceName
  **/
  @Schema(description = "")
  public String getInstanceName() {
    return instanceName;
  }

  public void setInstanceName(String instanceName) {
    this.instanceName = instanceName;
  }

  public InstancesInfoForDescribeInstancesOutput instanceStatus(String instanceStatus) {
    this.instanceStatus = instanceStatus;
    return this;
  }

   /**
   * Get instanceStatus
   * @return instanceStatus
  **/
  @Schema(description = "")
  public String getInstanceStatus() {
    return instanceStatus;
  }

  public void setInstanceStatus(String instanceStatus) {
    this.instanceStatus = instanceStatus;
  }

  public InstancesInfoForDescribeInstancesOutput instanceTags(List<InstanceTagForDescribeInstancesOutput> instanceTags) {
    this.instanceTags = instanceTags;
    return this;
  }

  public InstancesInfoForDescribeInstancesOutput addInstanceTagsItem(InstanceTagForDescribeInstancesOutput instanceTagsItem) {
    if (this.instanceTags == null) {
      this.instanceTags = new ArrayList<InstanceTagForDescribeInstancesOutput>();
    }
    this.instanceTags.add(instanceTagsItem);
    return this;
  }

   /**
   * Get instanceTags
   * @return instanceTags
  **/
  @Valid
  @Schema(description = "")
  public List<InstanceTagForDescribeInstancesOutput> getInstanceTags() {
    return instanceTags;
  }

  public void setInstanceTags(List<InstanceTagForDescribeInstancesOutput> instanceTags) {
    this.instanceTags = instanceTags;
  }

  public InstancesInfoForDescribeInstancesOutput projectName(String projectName) {
    this.projectName = projectName;
    return this;
  }

   /**
   * Get projectName
   * @return projectName
  **/
  @Schema(description = "")
  public String getProjectName() {
    return projectName;
  }

  public void setProjectName(String projectName) {
    this.projectName = projectName;
  }

  public InstancesInfoForDescribeInstancesOutput regionId(String regionId) {
    this.regionId = regionId;
    return this;
  }

   /**
   * Get regionId
   * @return regionId
  **/
  @Schema(description = "")
  public String getRegionId() {
    return regionId;
  }

  public void setRegionId(String regionId) {
    this.regionId = regionId;
  }

  public InstancesInfoForDescribeInstancesOutput ssLMode(String ssLMode) {
    this.ssLMode = ssLMode;
    return this;
  }

   /**
   * Get ssLMode
   * @return ssLMode
  **/
  @Schema(description = "")
  public String getSsLMode() {
    return ssLMode;
  }

  public void setSsLMode(String ssLMode) {
    this.ssLMode = ssLMode;
  }

  public InstancesInfoForDescribeInstancesOutput storageSpace(Integer storageSpace) {
    this.storageSpace = storageSpace;
    return this;
  }

   /**
   * Get storageSpace
   * @return storageSpace
  **/
  @Schema(description = "")
  public Integer getStorageSpace() {
    return storageSpace;
  }

  public void setStorageSpace(Integer storageSpace) {
    this.storageSpace = storageSpace;
  }

  public InstancesInfoForDescribeInstancesOutput subnetId(String subnetId) {
    this.subnetId = subnetId;
    return this;
  }

   /**
   * Get subnetId
   * @return subnetId
  **/
  @Schema(description = "")
  public String getSubnetId() {
    return subnetId;
  }

  public void setSubnetId(String subnetId) {
    this.subnetId = subnetId;
  }

  public InstancesInfoForDescribeInstancesOutput usedGroupNumber(Integer usedGroupNumber) {
    this.usedGroupNumber = usedGroupNumber;
    return this;
  }

   /**
   * Get usedGroupNumber
   * @return usedGroupNumber
  **/
  @Schema(description = "")
  public Integer getUsedGroupNumber() {
    return usedGroupNumber;
  }

  public void setUsedGroupNumber(Integer usedGroupNumber) {
    this.usedGroupNumber = usedGroupNumber;
  }

  public InstancesInfoForDescribeInstancesOutput usedQueueNumber(Integer usedQueueNumber) {
    this.usedQueueNumber = usedQueueNumber;
    return this;
  }

   /**
   * Get usedQueueNumber
   * @return usedQueueNumber
  **/
  @Schema(description = "")
  public Integer getUsedQueueNumber() {
    return usedQueueNumber;
  }

  public void setUsedQueueNumber(Integer usedQueueNumber) {
    this.usedQueueNumber = usedQueueNumber;
  }

  public InstancesInfoForDescribeInstancesOutput usedStorageSpace(Integer usedStorageSpace) {
    this.usedStorageSpace = usedStorageSpace;
    return this;
  }

   /**
   * Get usedStorageSpace
   * @return usedStorageSpace
  **/
  @Schema(description = "")
  public Integer getUsedStorageSpace() {
    return usedStorageSpace;
  }

  public void setUsedStorageSpace(Integer usedStorageSpace) {
    this.usedStorageSpace = usedStorageSpace;
  }

  public InstancesInfoForDescribeInstancesOutput usedTopicNumber(Integer usedTopicNumber) {
    this.usedTopicNumber = usedTopicNumber;
    return this;
  }

   /**
   * Get usedTopicNumber
   * @return usedTopicNumber
  **/
  @Schema(description = "")
  public Integer getUsedTopicNumber() {
    return usedTopicNumber;
  }

  public void setUsedTopicNumber(Integer usedTopicNumber) {
    this.usedTopicNumber = usedTopicNumber;
  }

  public InstancesInfoForDescribeInstancesOutput version(String version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @Schema(description = "")
  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }

  public InstancesInfoForDescribeInstancesOutput vpcId(String vpcId) {
    this.vpcId = vpcId;
    return this;
  }

   /**
   * Get vpcId
   * @return vpcId
  **/
  @Schema(description = "")
  public String getVpcId() {
    return vpcId;
  }

  public void setVpcId(String vpcId) {
    this.vpcId = vpcId;
  }

  public InstancesInfoForDescribeInstancesOutput zoneId(String zoneId) {
    this.zoneId = zoneId;
    return this;
  }

   /**
   * Get zoneId
   * @return zoneId
  **/
  @Schema(description = "")
  public String getZoneId() {
    return zoneId;
  }

  public void setZoneId(String zoneId) {
    this.zoneId = zoneId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InstancesInfoForDescribeInstancesOutput instancesInfoForDescribeInstancesOutput = (InstancesInfoForDescribeInstancesOutput) o;
    return Objects.equals(this.accountId, instancesInfoForDescribeInstancesOutput.accountId) &&
        Objects.equals(this.applyPrivateDNSToPublic, instancesInfoForDescribeInstancesOutput.applyPrivateDNSToPublic) &&
        Objects.equals(this.availableQueueNumber, instancesInfoForDescribeInstancesOutput.availableQueueNumber) &&
        Objects.equals(this.chargeDetail, instancesInfoForDescribeInstancesOutput.chargeDetail) &&
        Objects.equals(this.computeSpec, instancesInfoForDescribeInstancesOutput.computeSpec) &&
        Objects.equals(this.createTime, instancesInfoForDescribeInstancesOutput.createTime) &&
        Objects.equals(this.eipId, instancesInfoForDescribeInstancesOutput.eipId) &&
        Objects.equals(this.enableSSL, instancesInfoForDescribeInstancesOutput.enableSSL) &&
        Objects.equals(this.fileReservedTime, instancesInfoForDescribeInstancesOutput.fileReservedTime) &&
        Objects.equals(this.instanceDescription, instancesInfoForDescribeInstancesOutput.instanceDescription) &&
        Objects.equals(this.instanceId, instancesInfoForDescribeInstancesOutput.instanceId) &&
        Objects.equals(this.instanceName, instancesInfoForDescribeInstancesOutput.instanceName) &&
        Objects.equals(this.instanceStatus, instancesInfoForDescribeInstancesOutput.instanceStatus) &&
        Objects.equals(this.instanceTags, instancesInfoForDescribeInstancesOutput.instanceTags) &&
        Objects.equals(this.projectName, instancesInfoForDescribeInstancesOutput.projectName) &&
        Objects.equals(this.regionId, instancesInfoForDescribeInstancesOutput.regionId) &&
        Objects.equals(this.ssLMode, instancesInfoForDescribeInstancesOutput.ssLMode) &&
        Objects.equals(this.storageSpace, instancesInfoForDescribeInstancesOutput.storageSpace) &&
        Objects.equals(this.subnetId, instancesInfoForDescribeInstancesOutput.subnetId) &&
        Objects.equals(this.usedGroupNumber, instancesInfoForDescribeInstancesOutput.usedGroupNumber) &&
        Objects.equals(this.usedQueueNumber, instancesInfoForDescribeInstancesOutput.usedQueueNumber) &&
        Objects.equals(this.usedStorageSpace, instancesInfoForDescribeInstancesOutput.usedStorageSpace) &&
        Objects.equals(this.usedTopicNumber, instancesInfoForDescribeInstancesOutput.usedTopicNumber) &&
        Objects.equals(this.version, instancesInfoForDescribeInstancesOutput.version) &&
        Objects.equals(this.vpcId, instancesInfoForDescribeInstancesOutput.vpcId) &&
        Objects.equals(this.zoneId, instancesInfoForDescribeInstancesOutput.zoneId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountId, applyPrivateDNSToPublic, availableQueueNumber, chargeDetail, computeSpec, createTime, eipId, enableSSL, fileReservedTime, instanceDescription, instanceId, instanceName, instanceStatus, instanceTags, projectName, regionId, ssLMode, storageSpace, subnetId, usedGroupNumber, usedQueueNumber, usedStorageSpace, usedTopicNumber, version, vpcId, zoneId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InstancesInfoForDescribeInstancesOutput {\n");
    
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    applyPrivateDNSToPublic: ").append(toIndentedString(applyPrivateDNSToPublic)).append("\n");
    sb.append("    availableQueueNumber: ").append(toIndentedString(availableQueueNumber)).append("\n");
    sb.append("    chargeDetail: ").append(toIndentedString(chargeDetail)).append("\n");
    sb.append("    computeSpec: ").append(toIndentedString(computeSpec)).append("\n");
    sb.append("    createTime: ").append(toIndentedString(createTime)).append("\n");
    sb.append("    eipId: ").append(toIndentedString(eipId)).append("\n");
    sb.append("    enableSSL: ").append(toIndentedString(enableSSL)).append("\n");
    sb.append("    fileReservedTime: ").append(toIndentedString(fileReservedTime)).append("\n");
    sb.append("    instanceDescription: ").append(toIndentedString(instanceDescription)).append("\n");
    sb.append("    instanceId: ").append(toIndentedString(instanceId)).append("\n");
    sb.append("    instanceName: ").append(toIndentedString(instanceName)).append("\n");
    sb.append("    instanceStatus: ").append(toIndentedString(instanceStatus)).append("\n");
    sb.append("    instanceTags: ").append(toIndentedString(instanceTags)).append("\n");
    sb.append("    projectName: ").append(toIndentedString(projectName)).append("\n");
    sb.append("    regionId: ").append(toIndentedString(regionId)).append("\n");
    sb.append("    ssLMode: ").append(toIndentedString(ssLMode)).append("\n");
    sb.append("    storageSpace: ").append(toIndentedString(storageSpace)).append("\n");
    sb.append("    subnetId: ").append(toIndentedString(subnetId)).append("\n");
    sb.append("    usedGroupNumber: ").append(toIndentedString(usedGroupNumber)).append("\n");
    sb.append("    usedQueueNumber: ").append(toIndentedString(usedQueueNumber)).append("\n");
    sb.append("    usedStorageSpace: ").append(toIndentedString(usedStorageSpace)).append("\n");
    sb.append("    usedTopicNumber: ").append(toIndentedString(usedTopicNumber)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    vpcId: ").append(toIndentedString(vpcId)).append("\n");
    sb.append("    zoneId: ").append(toIndentedString(zoneId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
