/*
 * dataleap20260301
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.volcengine.dataleap20260301.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.volcengine.dataleap20260301.model.DataForGetEmrAccountRelationByInternalIdOutput;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * GetEmrAccountRelationByInternalIdResponse
 */



public class GetEmrAccountRelationByInternalIdResponse extends com.volcengine.model.AbstractResponse {
  @SerializedName("Code")
  private Integer code = null;

  @SerializedName("Data")
  private DataForGetEmrAccountRelationByInternalIdOutput data = null;

  @SerializedName("Message")
  private String message = null;

  @SerializedName("Timestamp")
  private Long timestamp = null;

  public GetEmrAccountRelationByInternalIdResponse code(Integer code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @Schema(description = "")
  public Integer getCode() {
    return code;
  }

  public void setCode(Integer code) {
    this.code = code;
  }

  public GetEmrAccountRelationByInternalIdResponse data(DataForGetEmrAccountRelationByInternalIdOutput data) {
    this.data = data;
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @Valid
  @Schema(description = "")
  public DataForGetEmrAccountRelationByInternalIdOutput getData() {
    return data;
  }

  public void setData(DataForGetEmrAccountRelationByInternalIdOutput data) {
    this.data = data;
  }

  public GetEmrAccountRelationByInternalIdResponse message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  @Schema(description = "")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public GetEmrAccountRelationByInternalIdResponse timestamp(Long timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Get timestamp
   * @return timestamp
  **/
  @Schema(description = "")
  public Long getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(Long timestamp) {
    this.timestamp = timestamp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetEmrAccountRelationByInternalIdResponse getEmrAccountRelationByInternalIdResponse = (GetEmrAccountRelationByInternalIdResponse) o;
    return Objects.equals(this.code, getEmrAccountRelationByInternalIdResponse.code) &&
        Objects.equals(this.data, getEmrAccountRelationByInternalIdResponse.data) &&
        Objects.equals(this.message, getEmrAccountRelationByInternalIdResponse.message) &&
        Objects.equals(this.timestamp, getEmrAccountRelationByInternalIdResponse.timestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, data, message, timestamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetEmrAccountRelationByInternalIdResponse {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
