/*
 * dataleap20260301
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.volcengine.dataleap20260301.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * ListSolutionsRequest
 */



public class ListSolutionsRequest {
  @SerializedName("CreateUserName")
  private String createUserName = null;

  @SerializedName("ExecutionStatus")
  private String executionStatus = null;

  @SerializedName("PageNumber")
  private Integer pageNumber = null;

  @SerializedName("PageSize")
  private Integer pageSize = null;

  @SerializedName("ProjectId")
  private Long projectId = null;

  @SerializedName("Queue")
  private String queue = null;

  @SerializedName("ReaderDataSourceName")
  private String readerDataSourceName = null;

  @SerializedName("ReaderDataSourceType")
  private String readerDataSourceType = null;

  @SerializedName("ResourceGroupName")
  private String resourceGroupName = null;

  @SerializedName("SolutionId")
  private Long solutionId = null;

  @SerializedName("SolutionName")
  private String solutionName = null;

  /**
   * Gets or Sets solutionType
   */
  @JsonAdapter(SolutionTypeEnum.Adapter.class)
  public enum SolutionTypeEnum {
    @SerializedName("SYNC_STREAMING_MULTI_SNAP_ONCE_INCR")
    SYNC_STREAMING_MULTI_SNAP_ONCE_INCR("SYNC_STREAMING_MULTI_SNAP_ONCE_INCR"),
    @SerializedName("SYNC_STREAMING_SHARDING_SNAP_ONCE_INCR")
    SYNC_STREAMING_SHARDING_SNAP_ONCE_INCR("SYNC_STREAMING_SHARDING_SNAP_ONCE_INCR"),
    @SerializedName("SYNC_BATCH_MULTI_SNAP_ONCE")
    SYNC_BATCH_MULTI_SNAP_ONCE("SYNC_BATCH_MULTI_SNAP_ONCE"),
    @SerializedName("SYNC_BATCH_MULTI_INCR_ONCE")
    SYNC_BATCH_MULTI_INCR_ONCE("SYNC_BATCH_MULTI_INCR_ONCE"),
    @SerializedName("SYNC_BATCH_MULTI_SNAP_CYCLE")
    SYNC_BATCH_MULTI_SNAP_CYCLE("SYNC_BATCH_MULTI_SNAP_CYCLE"),
    @SerializedName("SYNC_BATCH_MULTI_INCR_CYCLE")
    SYNC_BATCH_MULTI_INCR_CYCLE("SYNC_BATCH_MULTI_INCR_CYCLE"),
    @SerializedName("SYNC_BATCH_MULTI_SNAP_ONCE_INCR_CYCLE")
    SYNC_BATCH_MULTI_SNAP_ONCE_INCR_CYCLE("SYNC_BATCH_MULTI_SNAP_ONCE_INCR_CYCLE"),
    @SerializedName("SYNC_BATCH_MULTI_TASK_MERGE_CYCLE")
    SYNC_BATCH_MULTI_TASK_MERGE_CYCLE("SYNC_BATCH_MULTI_TASK_MERGE_CYCLE"),
    @SerializedName("SYNC_STREAMING_TASK_INGE")
    SYNC_STREAMING_TASK_INGE("SYNC_STREAMING_TASK_INGE");

    private String value;

    SolutionTypeEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static SolutionTypeEnum fromValue(String input) {
      for (SolutionTypeEnum b : SolutionTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<SolutionTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final SolutionTypeEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public SolutionTypeEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return SolutionTypeEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("SolutionType")
  private SolutionTypeEnum solutionType = null;

  @SerializedName("SortColumn")
  private String sortColumn = null;

  /**
   * Gets or Sets sortOrder
   */
  @JsonAdapter(SortOrderEnum.Adapter.class)
  public enum SortOrderEnum {
    @SerializedName("asc")
    ASC("asc"),
    @SerializedName("desc")
    DESC("desc");

    private String value;

    SortOrderEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static SortOrderEnum fromValue(String input) {
      for (SortOrderEnum b : SortOrderEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<SortOrderEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final SortOrderEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public SortOrderEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return SortOrderEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("SortOrder")
  private SortOrderEnum sortOrder = null;

  @SerializedName("WriterDataSourceName")
  private String writerDataSourceName = null;

  @SerializedName("WriterDataSourceType")
  private String writerDataSourceType = null;

  public ListSolutionsRequest createUserName(String createUserName) {
    this.createUserName = createUserName;
    return this;
  }

   /**
   * Get createUserName
   * @return createUserName
  **/
  @Schema(description = "")
  public String getCreateUserName() {
    return createUserName;
  }

  public void setCreateUserName(String createUserName) {
    this.createUserName = createUserName;
  }

  public ListSolutionsRequest executionStatus(String executionStatus) {
    this.executionStatus = executionStatus;
    return this;
  }

   /**
   * Get executionStatus
   * @return executionStatus
  **/
  @Schema(description = "")
  public String getExecutionStatus() {
    return executionStatus;
  }

  public void setExecutionStatus(String executionStatus) {
    this.executionStatus = executionStatus;
  }

  public ListSolutionsRequest pageNumber(Integer pageNumber) {
    this.pageNumber = pageNumber;
    return this;
  }

   /**
   * Get pageNumber
   * @return pageNumber
  **/
  @NotNull
  @Schema(required = true, description = "")
  public Integer getPageNumber() {
    return pageNumber;
  }

  public void setPageNumber(Integer pageNumber) {
    this.pageNumber = pageNumber;
  }

  public ListSolutionsRequest pageSize(Integer pageSize) {
    this.pageSize = pageSize;
    return this;
  }

   /**
   * Get pageSize
   * @return pageSize
  **/
  @NotNull
  @Schema(required = true, description = "")
  public Integer getPageSize() {
    return pageSize;
  }

  public void setPageSize(Integer pageSize) {
    this.pageSize = pageSize;
  }

  public ListSolutionsRequest projectId(Long projectId) {
    this.projectId = projectId;
    return this;
  }

   /**
   * Get projectId
   * @return projectId
  **/
  @NotNull
  @Schema(required = true, description = "")
  public Long getProjectId() {
    return projectId;
  }

  public void setProjectId(Long projectId) {
    this.projectId = projectId;
  }

  public ListSolutionsRequest queue(String queue) {
    this.queue = queue;
    return this;
  }

   /**
   * Get queue
   * @return queue
  **/
  @Schema(description = "")
  public String getQueue() {
    return queue;
  }

  public void setQueue(String queue) {
    this.queue = queue;
  }

  public ListSolutionsRequest readerDataSourceName(String readerDataSourceName) {
    this.readerDataSourceName = readerDataSourceName;
    return this;
  }

   /**
   * Get readerDataSourceName
   * @return readerDataSourceName
  **/
  @Schema(description = "")
  public String getReaderDataSourceName() {
    return readerDataSourceName;
  }

  public void setReaderDataSourceName(String readerDataSourceName) {
    this.readerDataSourceName = readerDataSourceName;
  }

  public ListSolutionsRequest readerDataSourceType(String readerDataSourceType) {
    this.readerDataSourceType = readerDataSourceType;
    return this;
  }

   /**
   * Get readerDataSourceType
   * @return readerDataSourceType
  **/
  @Schema(description = "")
  public String getReaderDataSourceType() {
    return readerDataSourceType;
  }

  public void setReaderDataSourceType(String readerDataSourceType) {
    this.readerDataSourceType = readerDataSourceType;
  }

  public ListSolutionsRequest resourceGroupName(String resourceGroupName) {
    this.resourceGroupName = resourceGroupName;
    return this;
  }

   /**
   * Get resourceGroupName
   * @return resourceGroupName
  **/
  @Schema(description = "")
  public String getResourceGroupName() {
    return resourceGroupName;
  }

  public void setResourceGroupName(String resourceGroupName) {
    this.resourceGroupName = resourceGroupName;
  }

  public ListSolutionsRequest solutionId(Long solutionId) {
    this.solutionId = solutionId;
    return this;
  }

   /**
   * Get solutionId
   * @return solutionId
  **/
  @Schema(description = "")
  public Long getSolutionId() {
    return solutionId;
  }

  public void setSolutionId(Long solutionId) {
    this.solutionId = solutionId;
  }

  public ListSolutionsRequest solutionName(String solutionName) {
    this.solutionName = solutionName;
    return this;
  }

   /**
   * Get solutionName
   * @return solutionName
  **/
  @Schema(description = "")
  public String getSolutionName() {
    return solutionName;
  }

  public void setSolutionName(String solutionName) {
    this.solutionName = solutionName;
  }

  public ListSolutionsRequest solutionType(SolutionTypeEnum solutionType) {
    this.solutionType = solutionType;
    return this;
  }

   /**
   * Get solutionType
   * @return solutionType
  **/
  @Schema(description = "")
  public SolutionTypeEnum getSolutionType() {
    return solutionType;
  }

  public void setSolutionType(SolutionTypeEnum solutionType) {
    this.solutionType = solutionType;
  }

  public ListSolutionsRequest sortColumn(String sortColumn) {
    this.sortColumn = sortColumn;
    return this;
  }

   /**
   * Get sortColumn
   * @return sortColumn
  **/
  @Schema(description = "")
  public String getSortColumn() {
    return sortColumn;
  }

  public void setSortColumn(String sortColumn) {
    this.sortColumn = sortColumn;
  }

  public ListSolutionsRequest sortOrder(SortOrderEnum sortOrder) {
    this.sortOrder = sortOrder;
    return this;
  }

   /**
   * Get sortOrder
   * @return sortOrder
  **/
  @Schema(description = "")
  public SortOrderEnum getSortOrder() {
    return sortOrder;
  }

  public void setSortOrder(SortOrderEnum sortOrder) {
    this.sortOrder = sortOrder;
  }

  public ListSolutionsRequest writerDataSourceName(String writerDataSourceName) {
    this.writerDataSourceName = writerDataSourceName;
    return this;
  }

   /**
   * Get writerDataSourceName
   * @return writerDataSourceName
  **/
  @Schema(description = "")
  public String getWriterDataSourceName() {
    return writerDataSourceName;
  }

  public void setWriterDataSourceName(String writerDataSourceName) {
    this.writerDataSourceName = writerDataSourceName;
  }

  public ListSolutionsRequest writerDataSourceType(String writerDataSourceType) {
    this.writerDataSourceType = writerDataSourceType;
    return this;
  }

   /**
   * Get writerDataSourceType
   * @return writerDataSourceType
  **/
  @Schema(description = "")
  public String getWriterDataSourceType() {
    return writerDataSourceType;
  }

  public void setWriterDataSourceType(String writerDataSourceType) {
    this.writerDataSourceType = writerDataSourceType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListSolutionsRequest listSolutionsRequest = (ListSolutionsRequest) o;
    return Objects.equals(this.createUserName, listSolutionsRequest.createUserName) &&
        Objects.equals(this.executionStatus, listSolutionsRequest.executionStatus) &&
        Objects.equals(this.pageNumber, listSolutionsRequest.pageNumber) &&
        Objects.equals(this.pageSize, listSolutionsRequest.pageSize) &&
        Objects.equals(this.projectId, listSolutionsRequest.projectId) &&
        Objects.equals(this.queue, listSolutionsRequest.queue) &&
        Objects.equals(this.readerDataSourceName, listSolutionsRequest.readerDataSourceName) &&
        Objects.equals(this.readerDataSourceType, listSolutionsRequest.readerDataSourceType) &&
        Objects.equals(this.resourceGroupName, listSolutionsRequest.resourceGroupName) &&
        Objects.equals(this.solutionId, listSolutionsRequest.solutionId) &&
        Objects.equals(this.solutionName, listSolutionsRequest.solutionName) &&
        Objects.equals(this.solutionType, listSolutionsRequest.solutionType) &&
        Objects.equals(this.sortColumn, listSolutionsRequest.sortColumn) &&
        Objects.equals(this.sortOrder, listSolutionsRequest.sortOrder) &&
        Objects.equals(this.writerDataSourceName, listSolutionsRequest.writerDataSourceName) &&
        Objects.equals(this.writerDataSourceType, listSolutionsRequest.writerDataSourceType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createUserName, executionStatus, pageNumber, pageSize, projectId, queue, readerDataSourceName, readerDataSourceType, resourceGroupName, solutionId, solutionName, solutionType, sortColumn, sortOrder, writerDataSourceName, writerDataSourceType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListSolutionsRequest {\n");
    
    sb.append("    createUserName: ").append(toIndentedString(createUserName)).append("\n");
    sb.append("    executionStatus: ").append(toIndentedString(executionStatus)).append("\n");
    sb.append("    pageNumber: ").append(toIndentedString(pageNumber)).append("\n");
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    queue: ").append(toIndentedString(queue)).append("\n");
    sb.append("    readerDataSourceName: ").append(toIndentedString(readerDataSourceName)).append("\n");
    sb.append("    readerDataSourceType: ").append(toIndentedString(readerDataSourceType)).append("\n");
    sb.append("    resourceGroupName: ").append(toIndentedString(resourceGroupName)).append("\n");
    sb.append("    solutionId: ").append(toIndentedString(solutionId)).append("\n");
    sb.append("    solutionName: ").append(toIndentedString(solutionName)).append("\n");
    sb.append("    solutionType: ").append(toIndentedString(solutionType)).append("\n");
    sb.append("    sortColumn: ").append(toIndentedString(sortColumn)).append("\n");
    sb.append("    sortOrder: ").append(toIndentedString(sortOrder)).append("\n");
    sb.append("    writerDataSourceName: ").append(toIndentedString(writerDataSourceName)).append("\n");
    sb.append("    writerDataSourceType: ").append(toIndentedString(writerDataSourceType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
