/*
 * apig
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.volcengine.apig.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.volcengine.apig.model.BackendTargetListForListUpstreamsOutput;
import com.volcengine.apig.model.CircuitBreakingSettingsForListUpstreamsOutput;
import com.volcengine.apig.model.LoadBalancerSettingsForListUpstreamsOutput;
import com.volcengine.apig.model.TlsSettingsForListUpstreamsOutput;
import com.volcengine.apig.model.UpstreamSpecForListUpstreamsOutput;
import com.volcengine.apig.model.VersionDetailForListUpstreamsOutput;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * ItemForListUpstreamsOutput
 */



public class ItemForListUpstreamsOutput {
  @SerializedName("BackendTargetList")
  private List<BackendTargetListForListUpstreamsOutput> backendTargetList = null;

  @SerializedName("CircuitBreakingSettings")
  private CircuitBreakingSettingsForListUpstreamsOutput circuitBreakingSettings = null;

  @SerializedName("Comments")
  private String comments = null;

  @SerializedName("CreateTime")
  private String createTime = null;

  @SerializedName("GatewayId")
  private String gatewayId = null;

  @SerializedName("Id")
  private String id = null;

  @SerializedName("LoadBalancerSettings")
  private LoadBalancerSettingsForListUpstreamsOutput loadBalancerSettings = null;

  @SerializedName("Name")
  private String name = null;

  @SerializedName("Protocol")
  private String protocol = null;

  @SerializedName("SourceType")
  private String sourceType = null;

  @SerializedName("TlsSettings")
  private TlsSettingsForListUpstreamsOutput tlsSettings = null;

  @SerializedName("UpdateTime")
  private String updateTime = null;

  @SerializedName("UpstreamSpec")
  private UpstreamSpecForListUpstreamsOutput upstreamSpec = null;

  @SerializedName("VersionDetails")
  private List<VersionDetailForListUpstreamsOutput> versionDetails = null;

  public ItemForListUpstreamsOutput backendTargetList(List<BackendTargetListForListUpstreamsOutput> backendTargetList) {
    this.backendTargetList = backendTargetList;
    return this;
  }

  public ItemForListUpstreamsOutput addBackendTargetListItem(BackendTargetListForListUpstreamsOutput backendTargetListItem) {
    if (this.backendTargetList == null) {
      this.backendTargetList = new ArrayList<BackendTargetListForListUpstreamsOutput>();
    }
    this.backendTargetList.add(backendTargetListItem);
    return this;
  }

   /**
   * Get backendTargetList
   * @return backendTargetList
  **/
  @Valid
  @Schema(description = "")
  public List<BackendTargetListForListUpstreamsOutput> getBackendTargetList() {
    return backendTargetList;
  }

  public void setBackendTargetList(List<BackendTargetListForListUpstreamsOutput> backendTargetList) {
    this.backendTargetList = backendTargetList;
  }

  public ItemForListUpstreamsOutput circuitBreakingSettings(CircuitBreakingSettingsForListUpstreamsOutput circuitBreakingSettings) {
    this.circuitBreakingSettings = circuitBreakingSettings;
    return this;
  }

   /**
   * Get circuitBreakingSettings
   * @return circuitBreakingSettings
  **/
  @Valid
  @Schema(description = "")
  public CircuitBreakingSettingsForListUpstreamsOutput getCircuitBreakingSettings() {
    return circuitBreakingSettings;
  }

  public void setCircuitBreakingSettings(CircuitBreakingSettingsForListUpstreamsOutput circuitBreakingSettings) {
    this.circuitBreakingSettings = circuitBreakingSettings;
  }

  public ItemForListUpstreamsOutput comments(String comments) {
    this.comments = comments;
    return this;
  }

   /**
   * Get comments
   * @return comments
  **/
  @Schema(description = "")
  public String getComments() {
    return comments;
  }

  public void setComments(String comments) {
    this.comments = comments;
  }

  public ItemForListUpstreamsOutput createTime(String createTime) {
    this.createTime = createTime;
    return this;
  }

   /**
   * Get createTime
   * @return createTime
  **/
  @Schema(description = "")
  public String getCreateTime() {
    return createTime;
  }

  public void setCreateTime(String createTime) {
    this.createTime = createTime;
  }

  public ItemForListUpstreamsOutput gatewayId(String gatewayId) {
    this.gatewayId = gatewayId;
    return this;
  }

   /**
   * Get gatewayId
   * @return gatewayId
  **/
  @Schema(description = "")
  public String getGatewayId() {
    return gatewayId;
  }

  public void setGatewayId(String gatewayId) {
    this.gatewayId = gatewayId;
  }

  public ItemForListUpstreamsOutput id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ItemForListUpstreamsOutput loadBalancerSettings(LoadBalancerSettingsForListUpstreamsOutput loadBalancerSettings) {
    this.loadBalancerSettings = loadBalancerSettings;
    return this;
  }

   /**
   * Get loadBalancerSettings
   * @return loadBalancerSettings
  **/
  @Valid
  @Schema(description = "")
  public LoadBalancerSettingsForListUpstreamsOutput getLoadBalancerSettings() {
    return loadBalancerSettings;
  }

  public void setLoadBalancerSettings(LoadBalancerSettingsForListUpstreamsOutput loadBalancerSettings) {
    this.loadBalancerSettings = loadBalancerSettings;
  }

  public ItemForListUpstreamsOutput name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ItemForListUpstreamsOutput protocol(String protocol) {
    this.protocol = protocol;
    return this;
  }

   /**
   * Get protocol
   * @return protocol
  **/
  @Schema(description = "")
  public String getProtocol() {
    return protocol;
  }

  public void setProtocol(String protocol) {
    this.protocol = protocol;
  }

  public ItemForListUpstreamsOutput sourceType(String sourceType) {
    this.sourceType = sourceType;
    return this;
  }

   /**
   * Get sourceType
   * @return sourceType
  **/
  @Schema(description = "")
  public String getSourceType() {
    return sourceType;
  }

  public void setSourceType(String sourceType) {
    this.sourceType = sourceType;
  }

  public ItemForListUpstreamsOutput tlsSettings(TlsSettingsForListUpstreamsOutput tlsSettings) {
    this.tlsSettings = tlsSettings;
    return this;
  }

   /**
   * Get tlsSettings
   * @return tlsSettings
  **/
  @Valid
  @Schema(description = "")
  public TlsSettingsForListUpstreamsOutput getTlsSettings() {
    return tlsSettings;
  }

  public void setTlsSettings(TlsSettingsForListUpstreamsOutput tlsSettings) {
    this.tlsSettings = tlsSettings;
  }

  public ItemForListUpstreamsOutput updateTime(String updateTime) {
    this.updateTime = updateTime;
    return this;
  }

   /**
   * Get updateTime
   * @return updateTime
  **/
  @Schema(description = "")
  public String getUpdateTime() {
    return updateTime;
  }

  public void setUpdateTime(String updateTime) {
    this.updateTime = updateTime;
  }

  public ItemForListUpstreamsOutput upstreamSpec(UpstreamSpecForListUpstreamsOutput upstreamSpec) {
    this.upstreamSpec = upstreamSpec;
    return this;
  }

   /**
   * Get upstreamSpec
   * @return upstreamSpec
  **/
  @Valid
  @Schema(description = "")
  public UpstreamSpecForListUpstreamsOutput getUpstreamSpec() {
    return upstreamSpec;
  }

  public void setUpstreamSpec(UpstreamSpecForListUpstreamsOutput upstreamSpec) {
    this.upstreamSpec = upstreamSpec;
  }

  public ItemForListUpstreamsOutput versionDetails(List<VersionDetailForListUpstreamsOutput> versionDetails) {
    this.versionDetails = versionDetails;
    return this;
  }

  public ItemForListUpstreamsOutput addVersionDetailsItem(VersionDetailForListUpstreamsOutput versionDetailsItem) {
    if (this.versionDetails == null) {
      this.versionDetails = new ArrayList<VersionDetailForListUpstreamsOutput>();
    }
    this.versionDetails.add(versionDetailsItem);
    return this;
  }

   /**
   * Get versionDetails
   * @return versionDetails
  **/
  @Valid
  @Schema(description = "")
  public List<VersionDetailForListUpstreamsOutput> getVersionDetails() {
    return versionDetails;
  }

  public void setVersionDetails(List<VersionDetailForListUpstreamsOutput> versionDetails) {
    this.versionDetails = versionDetails;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ItemForListUpstreamsOutput itemForListUpstreamsOutput = (ItemForListUpstreamsOutput) o;
    return Objects.equals(this.backendTargetList, itemForListUpstreamsOutput.backendTargetList) &&
        Objects.equals(this.circuitBreakingSettings, itemForListUpstreamsOutput.circuitBreakingSettings) &&
        Objects.equals(this.comments, itemForListUpstreamsOutput.comments) &&
        Objects.equals(this.createTime, itemForListUpstreamsOutput.createTime) &&
        Objects.equals(this.gatewayId, itemForListUpstreamsOutput.gatewayId) &&
        Objects.equals(this.id, itemForListUpstreamsOutput.id) &&
        Objects.equals(this.loadBalancerSettings, itemForListUpstreamsOutput.loadBalancerSettings) &&
        Objects.equals(this.name, itemForListUpstreamsOutput.name) &&
        Objects.equals(this.protocol, itemForListUpstreamsOutput.protocol) &&
        Objects.equals(this.sourceType, itemForListUpstreamsOutput.sourceType) &&
        Objects.equals(this.tlsSettings, itemForListUpstreamsOutput.tlsSettings) &&
        Objects.equals(this.updateTime, itemForListUpstreamsOutput.updateTime) &&
        Objects.equals(this.upstreamSpec, itemForListUpstreamsOutput.upstreamSpec) &&
        Objects.equals(this.versionDetails, itemForListUpstreamsOutput.versionDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(backendTargetList, circuitBreakingSettings, comments, createTime, gatewayId, id, loadBalancerSettings, name, protocol, sourceType, tlsSettings, updateTime, upstreamSpec, versionDetails);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ItemForListUpstreamsOutput {\n");
    
    sb.append("    backendTargetList: ").append(toIndentedString(backendTargetList)).append("\n");
    sb.append("    circuitBreakingSettings: ").append(toIndentedString(circuitBreakingSettings)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    createTime: ").append(toIndentedString(createTime)).append("\n");
    sb.append("    gatewayId: ").append(toIndentedString(gatewayId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    loadBalancerSettings: ").append(toIndentedString(loadBalancerSettings)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    protocol: ").append(toIndentedString(protocol)).append("\n");
    sb.append("    sourceType: ").append(toIndentedString(sourceType)).append("\n");
    sb.append("    tlsSettings: ").append(toIndentedString(tlsSettings)).append("\n");
    sb.append("    updateTime: ").append(toIndentedString(updateTime)).append("\n");
    sb.append("    upstreamSpec: ").append(toIndentedString(upstreamSpec)).append("\n");
    sb.append("    versionDetails: ").append(toIndentedString(versionDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
