/*
 * insight
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.volcengine.insight.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * ExpertInvokeAPIRequest
 */



public class ExpertInvokeAPIRequest {
  @SerializedName("Asr")
  private String asr = null;

  @SerializedName("ClassifiedAgentId")
  private Long classifiedAgentId = null;

  @SerializedName("ConfigId")
  private Long configId = null;

  @SerializedName("Content")
  private String content = null;

  @SerializedName("DomainLevel")
  private Integer domainLevel = null;

  @SerializedName("ExpertId")
  private Long expertId = null;

  @SerializedName("FansCnt")
  private Long fansCnt = null;

  @SerializedName("Ocr")
  private String ocr = null;

  @SerializedName("OriginId")
  private String originId = null;

  @SerializedName("Title")
  private String title = null;

  @SerializedName("Url")
  private String url = null;

  public ExpertInvokeAPIRequest asr(String asr) {
    this.asr = asr;
    return this;
  }

   /**
   * Get asr
   * @return asr
  **/
  @Schema(description = "")
  public String getAsr() {
    return asr;
  }

  public void setAsr(String asr) {
    this.asr = asr;
  }

  public ExpertInvokeAPIRequest classifiedAgentId(Long classifiedAgentId) {
    this.classifiedAgentId = classifiedAgentId;
    return this;
  }

   /**
   * Get classifiedAgentId
   * @return classifiedAgentId
  **/
  @Schema(description = "")
  public Long getClassifiedAgentId() {
    return classifiedAgentId;
  }

  public void setClassifiedAgentId(Long classifiedAgentId) {
    this.classifiedAgentId = classifiedAgentId;
  }

  public ExpertInvokeAPIRequest configId(Long configId) {
    this.configId = configId;
    return this;
  }

   /**
   * Get configId
   * @return configId
  **/
  @Schema(description = "")
  public Long getConfigId() {
    return configId;
  }

  public void setConfigId(Long configId) {
    this.configId = configId;
  }

  public ExpertInvokeAPIRequest content(String content) {
    this.content = content;
    return this;
  }

   /**
   * Get content
   * @return content
  **/
  @Schema(description = "")
  public String getContent() {
    return content;
  }

  public void setContent(String content) {
    this.content = content;
  }

  public ExpertInvokeAPIRequest domainLevel(Integer domainLevel) {
    this.domainLevel = domainLevel;
    return this;
  }

   /**
   * Get domainLevel
   * @return domainLevel
  **/
  @Schema(description = "")
  public Integer getDomainLevel() {
    return domainLevel;
  }

  public void setDomainLevel(Integer domainLevel) {
    this.domainLevel = domainLevel;
  }

  public ExpertInvokeAPIRequest expertId(Long expertId) {
    this.expertId = expertId;
    return this;
  }

   /**
   * Get expertId
   * @return expertId
  **/
  @NotNull
  @Schema(required = true, description = "")
  public Long getExpertId() {
    return expertId;
  }

  public void setExpertId(Long expertId) {
    this.expertId = expertId;
  }

  public ExpertInvokeAPIRequest fansCnt(Long fansCnt) {
    this.fansCnt = fansCnt;
    return this;
  }

   /**
   * Get fansCnt
   * @return fansCnt
  **/
  @Schema(description = "")
  public Long getFansCnt() {
    return fansCnt;
  }

  public void setFansCnt(Long fansCnt) {
    this.fansCnt = fansCnt;
  }

  public ExpertInvokeAPIRequest ocr(String ocr) {
    this.ocr = ocr;
    return this;
  }

   /**
   * Get ocr
   * @return ocr
  **/
  @Schema(description = "")
  public String getOcr() {
    return ocr;
  }

  public void setOcr(String ocr) {
    this.ocr = ocr;
  }

  public ExpertInvokeAPIRequest originId(String originId) {
    this.originId = originId;
    return this;
  }

   /**
   * Get originId
   * @return originId
  **/
  @Schema(description = "")
  public String getOriginId() {
    return originId;
  }

  public void setOriginId(String originId) {
    this.originId = originId;
  }

  public ExpertInvokeAPIRequest title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @Schema(description = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public ExpertInvokeAPIRequest url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @Schema(description = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExpertInvokeAPIRequest expertInvokeAPIRequest = (ExpertInvokeAPIRequest) o;
    return Objects.equals(this.asr, expertInvokeAPIRequest.asr) &&
        Objects.equals(this.classifiedAgentId, expertInvokeAPIRequest.classifiedAgentId) &&
        Objects.equals(this.configId, expertInvokeAPIRequest.configId) &&
        Objects.equals(this.content, expertInvokeAPIRequest.content) &&
        Objects.equals(this.domainLevel, expertInvokeAPIRequest.domainLevel) &&
        Objects.equals(this.expertId, expertInvokeAPIRequest.expertId) &&
        Objects.equals(this.fansCnt, expertInvokeAPIRequest.fansCnt) &&
        Objects.equals(this.ocr, expertInvokeAPIRequest.ocr) &&
        Objects.equals(this.originId, expertInvokeAPIRequest.originId) &&
        Objects.equals(this.title, expertInvokeAPIRequest.title) &&
        Objects.equals(this.url, expertInvokeAPIRequest.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(asr, classifiedAgentId, configId, content, domainLevel, expertId, fansCnt, ocr, originId, title, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExpertInvokeAPIRequest {\n");
    
    sb.append("    asr: ").append(toIndentedString(asr)).append("\n");
    sb.append("    classifiedAgentId: ").append(toIndentedString(classifiedAgentId)).append("\n");
    sb.append("    configId: ").append(toIndentedString(configId)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    domainLevel: ").append(toIndentedString(domainLevel)).append("\n");
    sb.append("    expertId: ").append(toIndentedString(expertId)).append("\n");
    sb.append("    fansCnt: ").append(toIndentedString(fansCnt)).append("\n");
    sb.append("    ocr: ").append(toIndentedString(ocr)).append("\n");
    sb.append("    originId: ").append(toIndentedString(originId)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
